import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { bindings } from './bindings.mjs';
import { kitSchemas, kitMethods, generateKitMethodTypes } from './kit-schema.mjs';

const root = new URL('../../', import.meta.url);
const catalog = JSON.parse(await readFile(new URL('crates/docs/api-index.json', root), 'utf8'));
const developer = JSON.parse(await readFile(new URL('crates/docs/developer-index.json', root), 'utf8'));
const jsOnly = process.argv.includes('--js-only');
const pendingAuthority = [];
const names = new Set(catalog.components.map(component => component.name));
for (const name of Object.keys(bindings)) if (!names.has(name)) throw new Error(`Binding has no Kit authority: ${name}`);
for (const component of catalog.components) {
  const signatures = ['construct', 'options', 'commands', 'queries'].flatMap(key => component[key] ?? []);
  for (const methods of Object.values(bindings[component.name]?.nativeMethods ?? {})) {
    for (const name of Object.keys(methods)) {
      const nativeName = bindings[component.name].nativeMethodSources?.[name] ?? name;
      if (nativeName.includes('::')) {
        // Queries on caller-owned data name the exact public method they call,
        // rather than pretending it is an inherent method of the component.
        if (developer.symbols.some(symbol => symbol.id === nativeName && symbol.kind === 'method')) continue;
        // Trait methods are deliberately absent from the inherent API index.
        // Name their trait authority explicitly; the native dispatcher compiles
        // the corresponding trait call on the concrete component type.
        const parts = nativeName.split('::'), method = parts.pop();
        const trait = developer.symbols.find(symbol => symbol.id === parts.join('::') && symbol.kind === 'trait');
        if (!trait || !trait.signature.includes(`fn ${method} (`)) throw new Error(`Native binding has no Rust trait authority: ${component.name}.${name}`);
        continue;
      }
      if (!signatures.some(signature => signature.startsWith(`${nativeName}(`))) {
        if (jsOnly && bindings[component.name].nativeIntegration === 'pending-central-hooks') {
          pendingAuthority.push(`${component.name}.${name}`);
        } else {
          throw new Error(`Native binding has no Rust method authority: ${component.name}.${name}`);
        }
      }
    }
  }
}
const components = catalog.components.map(component => ({
  name: component.name,
  source: component.source,
  path: component.path,
  binding: bindings[component.name] ?? { status: 'unbound', reason: 'Native adapter and behavioral tests not implemented' },
  rustSignatures: Object.fromEntries(['construct', 'options', 'commands', 'queries', 'slots'].map(key => [key, component[key] ?? []])),
}));
const json = JSON.stringify({ schema: 1, authority: 'crates/docs/api-index.json', components }, null, 2) + '\n';
// These types describe coverage and retain source handles; unbound components are
// not counterfeit constructors. Runtime APIs are declared separately in sdk.d.ts.
const declarations = '// Generated by catalog.mjs. Coverage metadata, not native constructors.\n' +
  'export interface KitBindingCatalog {\n' + components.map(c =>
    `  readonly ${JSON.stringify(c.name)}: { readonly source: ${JSON.stringify(c.source)}; readonly status: ${JSON.stringify(c.binding.status)} };`
  ).join('\n') + '\n}\nexport type KitComponentName = keyof KitBindingCatalog;\n';
const sdk = await readFile(new URL('kit-sdk.d.ts', import.meta.url), 'utf8');
const marker = '// Generated from kitMethods';
if (!sdk.includes(marker)) throw new Error('Missing generated method boundary');
// JS-only integration can review contracts without asserting native registration.
// The default generation/check still includes both embedded native documents.
const nativeArtifacts = jsOnly ? [] : [
  ['../app-host/src/kit_bindings/schemas.json', JSON.stringify(kitSchemas, null, 2) + '\n'],
  ['../app-host/src/kit_bindings/methods.json', JSON.stringify(kitMethods, null, 2) + '\n'],
];
for (const [name, contents] of [
  ['binding-coverage.json', json], ['catalog.d.ts', declarations],
  ...nativeArtifacts,
  ['kit-sdk.d.ts', sdk.slice(0, sdk.indexOf(marker)) + generateKitMethodTypes()],
]) {
  const path = new URL(name, import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8') !== contents) throw new Error(`Stale ${fileURLToPath(path)}; run node tools/js-runtime/catalog.mjs`);
  } else { await writeFile(path, contents); }
}
console.log(`Kit binding coverage: ${components.filter(c => c.binding.status !== 'unbound').length}/${components.length} declared adapters; native integration and fallback limits recorded per component`);
if (jsOnly) {
  console.log('JS-only: native embedded schemas/methods were not generated or checked');
  if (pendingAuthority.length) console.log(`Pending regenerated Rust method authority: ${pendingAuthority.join(', ')}`);
}
