//! Generated by `cargo run -p xtask -- icons generate`; do not edit.
use std::borrow::Cow;

pub const PHOSPHOR_VERSION: &str = "2.1.1";
pub const PHOSPHOR_REVISION: &str = "2b75f3ad12b420c9504ef05df8d2564a28f8500e";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mirroring {
    Directional,
    Fixed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IconWeight {
    Regular,
    Fill,
}

impl IconWeight {
    pub const ALL: &'static [Self] = &[Self::Regular, Self::Fill];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IconName {
    AddCircle,
    AltArrowDown,
    AltArrowLeft,
    AltArrowRight,
    Archive,
    ArchiveUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Browser,
    Calendar,
    CalendarDots,
    Chat,
    Check,
    CheckboxChecked,
    CheckboxEmpty,
    CheckCircle,
    Checklist,
    ClockCountdown,
    Close,
    CloseCircle,
    Command,
    Copy,
    CornersIn,
    Danger,
    Document,
    DocumentAdd,
    DoubleArrowLeft,
    DoubleArrowRight,
    DragHandle,
    ExternalLink,
    Filter,
    Folder,
    Forbidden,
    FolderWithFiles,
    GitBranch,
    GitDiff,
    Global,
    Graph,
    Home,
    Image,
    Info,
    Key,
    Keyboard,
    Laptop,
    List,
    Logout,
    Magnifier,
    Minus,
    Monitor,
    MoreHorizontal,
    Notebook,
    Paperclip,
    Pause,
    Pen,
    PenNew,
    Play,
    Plus,
    Refresh,
    Restart,
    Return,
    Settings,
    Sidebar,
    SidebarLeft,
    Smartphone,
    SortVertical,
    Sparkle,
    Spinner,
    Star,
    SoundWave,
    Stop,
    Terminal,
    Trash,
    Tuning,
    Video,
    Widget,
}

impl IconName {
    pub const ALL: &'static [Self] = &[
        Self::AddCircle,
        Self::AltArrowDown,
        Self::AltArrowLeft,
        Self::AltArrowRight,
        Self::Archive,
        Self::ArchiveUp,
        Self::ArrowDown,
        Self::ArrowLeft,
        Self::ArrowRight,
        Self::ArrowUp,
        Self::Browser,
        Self::Calendar,
        Self::CalendarDots,
        Self::Chat,
        Self::Check,
        Self::CheckboxChecked,
        Self::CheckboxEmpty,
        Self::CheckCircle,
        Self::Checklist,
        Self::ClockCountdown,
        Self::Close,
        Self::CloseCircle,
        Self::Command,
        Self::Copy,
        Self::CornersIn,
        Self::Danger,
        Self::Document,
        Self::DocumentAdd,
        Self::DoubleArrowLeft,
        Self::DoubleArrowRight,
        Self::DragHandle,
        Self::ExternalLink,
        Self::Filter,
        Self::Folder,
        Self::Forbidden,
        Self::FolderWithFiles,
        Self::GitBranch,
        Self::GitDiff,
        Self::Global,
        Self::Graph,
        Self::Home,
        Self::Image,
        Self::Info,
        Self::Key,
        Self::Keyboard,
        Self::Laptop,
        Self::List,
        Self::Logout,
        Self::Magnifier,
        Self::Minus,
        Self::Monitor,
        Self::MoreHorizontal,
        Self::Notebook,
        Self::Paperclip,
        Self::Pause,
        Self::Pen,
        Self::PenNew,
        Self::Play,
        Self::Plus,
        Self::Refresh,
        Self::Restart,
        Self::Return,
        Self::Settings,
        Self::Sidebar,
        Self::SidebarLeft,
        Self::Smartphone,
        Self::SortVertical,
        Self::Sparkle,
        Self::Spinner,
        Self::Star,
        Self::SoundWave,
        Self::Stop,
        Self::Terminal,
        Self::Trash,
        Self::Tuning,
        Self::Video,
        Self::Widget,
    ];

    pub const fn source_name(self) -> &'static str {
        match self {
            Self::AddCircle => "plus-circle",
            Self::AltArrowDown => "caret-down",
            Self::AltArrowLeft => "caret-left",
            Self::AltArrowRight => "caret-right",
            Self::Archive => "archive",
            Self::ArchiveUp => "box-arrow-up",
            Self::ArrowDown => "arrow-down",
            Self::ArrowLeft => "arrow-left",
            Self::ArrowRight => "arrow-right",
            Self::ArrowUp => "arrow-up",
            Self::Browser => "browser",
            Self::Calendar => "calendar",
            Self::CalendarDots => "calendar-dots",
            Self::Chat => "chat-circle-text",
            Self::Check => "check",
            Self::CheckboxChecked => "check-square",
            Self::CheckboxEmpty => "square",
            Self::CheckCircle => "check-circle",
            Self::Checklist => "list-checks",
            Self::ClockCountdown => "clock-countdown",
            Self::Close => "x",
            Self::CloseCircle => "x-circle",
            Self::Command => "command",
            Self::Copy => "copy",
            Self::CornersIn => "corners-in",
            Self::Danger => "warning",
            Self::Document => "file-text",
            Self::DocumentAdd => "file-plus",
            Self::DoubleArrowLeft => "caret-double-left",
            Self::DoubleArrowRight => "caret-double-right",
            Self::DragHandle => "dots-six-vertical",
            Self::ExternalLink => "arrow-square-out",
            Self::Filter => "funnel-simple",
            Self::Folder => "folder",
            Self::Forbidden => "prohibit",
            Self::FolderWithFiles => "folders",
            Self::GitBranch => "git-branch",
            Self::GitDiff => "git-diff",
            Self::Global => "globe",
            Self::Graph => "graph",
            Self::Home => "house",
            Self::Image => "image",
            Self::Info => "info",
            Self::Key => "key",
            Self::Keyboard => "keyboard",
            Self::Laptop => "laptop",
            Self::List => "list",
            Self::Logout => "sign-out",
            Self::Magnifier => "magnifying-glass",
            Self::Minus => "minus",
            Self::Monitor => "monitor",
            Self::MoreHorizontal => "dots-three",
            Self::Notebook => "notebook",
            Self::Paperclip => "paperclip",
            Self::Pause => "pause",
            Self::Pen => "pencil-simple",
            Self::PenNew => "note-pencil",
            Self::Play => "play",
            Self::Plus => "plus",
            Self::Refresh => "arrow-clockwise",
            Self::Restart => "arrows-counter-clockwise",
            Self::Return => "arrow-bend-up-left",
            Self::Settings => "gear-six",
            Self::Sidebar => "sidebar",
            Self::SidebarLeft => "sidebar-simple",
            Self::Smartphone => "device-mobile",
            Self::SortVertical => "arrows-down-up",
            Self::Sparkle => "sparkle",
            Self::Spinner => "spinner-gap",
            Self::Star => "star",
            Self::SoundWave => "waveform",
            Self::Stop => "stop",
            Self::Terminal => "terminal-window",
            Self::Trash => "trash",
            Self::Tuning => "sliders-horizontal",
            Self::Video => "video-camera",
            Self::Widget => "squares-four",
        }
    }

    pub const fn mirroring(self) -> Mirroring {
        match self {
            Self::AddCircle => Mirroring::Fixed,
            Self::AltArrowDown => Mirroring::Fixed,
            Self::AltArrowLeft => Mirroring::Directional,
            Self::AltArrowRight => Mirroring::Directional,
            Self::Archive => Mirroring::Fixed,
            Self::ArchiveUp => Mirroring::Fixed,
            Self::ArrowDown => Mirroring::Fixed,
            Self::ArrowLeft => Mirroring::Directional,
            Self::ArrowRight => Mirroring::Directional,
            Self::ArrowUp => Mirroring::Fixed,
            Self::Browser => Mirroring::Fixed,
            Self::Calendar => Mirroring::Fixed,
            Self::CalendarDots => Mirroring::Fixed,
            Self::Chat => Mirroring::Directional,
            Self::Check => Mirroring::Fixed,
            Self::CheckboxChecked => Mirroring::Fixed,
            Self::CheckboxEmpty => Mirroring::Fixed,
            Self::CheckCircle => Mirroring::Fixed,
            Self::Checklist => Mirroring::Directional,
            Self::ClockCountdown => Mirroring::Fixed,
            Self::Close => Mirroring::Fixed,
            Self::CloseCircle => Mirroring::Fixed,
            Self::Command => Mirroring::Fixed,
            Self::Copy => Mirroring::Directional,
            Self::CornersIn => Mirroring::Fixed,
            Self::Danger => Mirroring::Fixed,
            Self::Document => Mirroring::Directional,
            Self::DocumentAdd => Mirroring::Directional,
            Self::DoubleArrowLeft => Mirroring::Directional,
            Self::DoubleArrowRight => Mirroring::Directional,
            Self::DragHandle => Mirroring::Fixed,
            Self::ExternalLink => Mirroring::Directional,
            Self::Filter => Mirroring::Fixed,
            Self::Folder => Mirroring::Directional,
            Self::Forbidden => Mirroring::Fixed,
            Self::FolderWithFiles => Mirroring::Directional,
            Self::GitBranch => Mirroring::Directional,
            Self::GitDiff => Mirroring::Directional,
            Self::Global => Mirroring::Fixed,
            Self::Graph => Mirroring::Fixed,
            Self::Home => Mirroring::Fixed,
            Self::Image => Mirroring::Fixed,
            Self::Info => Mirroring::Fixed,
            Self::Key => Mirroring::Directional,
            Self::Keyboard => Mirroring::Fixed,
            Self::Laptop => Mirroring::Fixed,
            Self::List => Mirroring::Directional,
            Self::Logout => Mirroring::Directional,
            Self::Magnifier => Mirroring::Directional,
            Self::Minus => Mirroring::Fixed,
            Self::Monitor => Mirroring::Fixed,
            Self::MoreHorizontal => Mirroring::Fixed,
            Self::Notebook => Mirroring::Fixed,
            Self::Paperclip => Mirroring::Directional,
            Self::Pause => Mirroring::Fixed,
            Self::Pen => Mirroring::Directional,
            Self::PenNew => Mirroring::Directional,
            Self::Play => Mirroring::Directional,
            Self::Plus => Mirroring::Fixed,
            Self::Refresh => Mirroring::Fixed,
            Self::Restart => Mirroring::Fixed,
            Self::Return => Mirroring::Directional,
            Self::Settings => Mirroring::Fixed,
            Self::Sidebar => Mirroring::Directional,
            Self::SidebarLeft => Mirroring::Directional,
            Self::Smartphone => Mirroring::Fixed,
            Self::SortVertical => Mirroring::Fixed,
            Self::Sparkle => Mirroring::Fixed,
            Self::Spinner => Mirroring::Fixed,
            Self::Star => Mirroring::Fixed,
            Self::SoundWave => Mirroring::Fixed,
            Self::Stop => Mirroring::Fixed,
            Self::Terminal => Mirroring::Directional,
            Self::Trash => Mirroring::Fixed,
            Self::Tuning => Mirroring::Fixed,
            Self::Video => Mirroring::Directional,
            Self::Widget => Mirroring::Fixed,
        }
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct Icon {
    name: IconName,
    weight: IconWeight,
}

#[allow(non_upper_case_globals)]
impl Icon {
    pub const ALL: &'static [Self] = &[
        Self::AddCircle,
        Self::AltArrowDown,
        Self::AltArrowLeft,
        Self::AltArrowRight,
        Self::Archive,
        Self::ArchiveUp,
        Self::ArrowDown,
        Self::ArrowLeft,
        Self::ArrowRight,
        Self::ArrowUp,
        Self::Browser,
        Self::Calendar,
        Self::CalendarDots,
        Self::Chat,
        Self::Check,
        Self::CheckboxChecked,
        Self::CheckboxEmpty,
        Self::CheckCircle,
        Self::Checklist,
        Self::ClockCountdown,
        Self::Close,
        Self::CloseCircle,
        Self::Command,
        Self::Copy,
        Self::CornersIn,
        Self::Danger,
        Self::Document,
        Self::DocumentAdd,
        Self::DoubleArrowLeft,
        Self::DoubleArrowRight,
        Self::DragHandle,
        Self::ExternalLink,
        Self::Filter,
        Self::Folder,
        Self::Forbidden,
        Self::FolderWithFiles,
        Self::GitBranch,
        Self::GitDiff,
        Self::Global,
        Self::Graph,
        Self::Home,
        Self::Image,
        Self::Info,
        Self::Key,
        Self::Keyboard,
        Self::Laptop,
        Self::List,
        Self::Logout,
        Self::Magnifier,
        Self::Minus,
        Self::Monitor,
        Self::MoreHorizontal,
        Self::Notebook,
        Self::Paperclip,
        Self::Pause,
        Self::Pen,
        Self::PenNew,
        Self::Play,
        Self::Plus,
        Self::Refresh,
        Self::Restart,
        Self::Return,
        Self::Settings,
        Self::Sidebar,
        Self::SidebarLeft,
        Self::Smartphone,
        Self::SortVertical,
        Self::Sparkle,
        Self::Spinner,
        Self::Star,
        Self::SoundWave,
        Self::Stop,
        Self::Terminal,
        Self::Trash,
        Self::Tuning,
        Self::Video,
        Self::Widget,
    ];

    pub const AddCircle: Self = Self::new(IconName::AddCircle);
    pub const AltArrowDown: Self = Self::new(IconName::AltArrowDown);
    pub const AltArrowLeft: Self = Self::new(IconName::AltArrowLeft);
    pub const AltArrowRight: Self = Self::new(IconName::AltArrowRight);
    pub const Archive: Self = Self::new(IconName::Archive);
    pub const ArchiveUp: Self = Self::new(IconName::ArchiveUp);
    pub const ArrowDown: Self = Self::new(IconName::ArrowDown);
    pub const ArrowLeft: Self = Self::new(IconName::ArrowLeft);
    pub const ArrowRight: Self = Self::new(IconName::ArrowRight);
    pub const ArrowUp: Self = Self::new(IconName::ArrowUp);
    pub const Browser: Self = Self::new(IconName::Browser);
    pub const Calendar: Self = Self::new(IconName::Calendar);
    pub const CalendarDots: Self = Self::new(IconName::CalendarDots);
    pub const Chat: Self = Self::new(IconName::Chat);
    pub const Check: Self = Self::new(IconName::Check);
    pub const CheckboxChecked: Self = Self::new(IconName::CheckboxChecked);
    pub const CheckboxEmpty: Self = Self::new(IconName::CheckboxEmpty);
    pub const CheckCircle: Self = Self::new(IconName::CheckCircle);
    pub const Checklist: Self = Self::new(IconName::Checklist);
    pub const ClockCountdown: Self = Self::new(IconName::ClockCountdown);
    pub const Close: Self = Self::new(IconName::Close);
    pub const CloseCircle: Self = Self::new(IconName::CloseCircle);
    pub const Command: Self = Self::new(IconName::Command);
    pub const Copy: Self = Self::new(IconName::Copy);
    pub const CornersIn: Self = Self::new(IconName::CornersIn);
    pub const Danger: Self = Self::new(IconName::Danger);
    pub const Document: Self = Self::new(IconName::Document);
    pub const DocumentAdd: Self = Self::new(IconName::DocumentAdd);
    pub const DoubleArrowLeft: Self = Self::new(IconName::DoubleArrowLeft);
    pub const DoubleArrowRight: Self = Self::new(IconName::DoubleArrowRight);
    pub const DragHandle: Self = Self::new(IconName::DragHandle);
    pub const ExternalLink: Self = Self::new(IconName::ExternalLink);
    pub const Filter: Self = Self::new(IconName::Filter);
    pub const Folder: Self = Self::new(IconName::Folder);
    pub const Forbidden: Self = Self::new(IconName::Forbidden);
    pub const FolderWithFiles: Self = Self::new(IconName::FolderWithFiles);
    pub const GitBranch: Self = Self::new(IconName::GitBranch);
    pub const GitDiff: Self = Self::new(IconName::GitDiff);
    pub const Global: Self = Self::new(IconName::Global);
    pub const Graph: Self = Self::new(IconName::Graph);
    pub const Home: Self = Self::new(IconName::Home);
    pub const Image: Self = Self::new(IconName::Image);
    pub const Info: Self = Self::new(IconName::Info);
    pub const Key: Self = Self::new(IconName::Key);
    pub const Keyboard: Self = Self::new(IconName::Keyboard);
    pub const Laptop: Self = Self::new(IconName::Laptop);
    pub const List: Self = Self::new(IconName::List);
    pub const Logout: Self = Self::new(IconName::Logout);
    pub const Magnifier: Self = Self::new(IconName::Magnifier);
    pub const Minus: Self = Self::new(IconName::Minus);
    pub const Monitor: Self = Self::new(IconName::Monitor);
    pub const MoreHorizontal: Self = Self::new(IconName::MoreHorizontal);
    pub const Notebook: Self = Self::new(IconName::Notebook);
    pub const Paperclip: Self = Self::new(IconName::Paperclip);
    pub const Pause: Self = Self::new(IconName::Pause);
    pub const Pen: Self = Self::new(IconName::Pen);
    pub const PenNew: Self = Self::new(IconName::PenNew);
    pub const Play: Self = Self::new(IconName::Play);
    pub const Plus: Self = Self::new(IconName::Plus);
    pub const Refresh: Self = Self::new(IconName::Refresh);
    pub const Restart: Self = Self::new(IconName::Restart);
    pub const Return: Self = Self::new(IconName::Return);
    pub const Settings: Self = Self::new(IconName::Settings);
    pub const Sidebar: Self = Self::new(IconName::Sidebar);
    pub const SidebarLeft: Self = Self::new(IconName::SidebarLeft);
    pub const Smartphone: Self = Self::new(IconName::Smartphone);
    pub const SortVertical: Self = Self::new(IconName::SortVertical);
    pub const Sparkle: Self = Self::new(IconName::Sparkle);
    pub const Spinner: Self = Self::new(IconName::Spinner);
    pub const Star: Self = Self::new(IconName::Star);
    pub const SoundWave: Self = Self::new(IconName::SoundWave);
    pub const Stop: Self = Self::new(IconName::Stop);
    pub const Terminal: Self = Self::new(IconName::Terminal);
    pub const Trash: Self = Self::new(IconName::Trash);
    pub const Tuning: Self = Self::new(IconName::Tuning);
    pub const Video: Self = Self::new(IconName::Video);
    pub const Widget: Self = Self::new(IconName::Widget);
    pub const StarFilled: Self = Self::Star.with_weight(IconWeight::Fill);

    pub const fn new(name: IconName) -> Self {
        Self {
            name,
            weight: IconWeight::Regular,
        }
    }
    pub const fn with_weight(self, weight: IconWeight) -> Self {
        Self { weight, ..self }
    }
    pub const fn filled(self) -> Self {
        self.with_weight(IconWeight::Fill)
    }
    pub const fn name(self) -> IconName {
        self.name
    }
    pub const fn weight(self) -> IconWeight {
        self.weight
    }
    pub const fn mirroring(self) -> Mirroring {
        self.name.mirroring()
    }
    pub const fn mirrors_in_rtl(self) -> bool {
        matches!(self.mirroring(), Mirroring::Directional)
    }

    pub const fn path(self) -> &'static str {
        match (self.name, self.weight) {
            (IconName::AddCircle, IconWeight::Regular) => "icons/regular/plus-circle.svg",
            (IconName::AddCircle, IconWeight::Fill) => "icons/fill/plus-circle-fill.svg",
            (IconName::AltArrowDown, IconWeight::Regular) => "icons/regular/caret-down.svg",
            (IconName::AltArrowDown, IconWeight::Fill) => "icons/fill/caret-down-fill.svg",
            (IconName::AltArrowLeft, IconWeight::Regular) => "icons/regular/caret-left.svg",
            (IconName::AltArrowLeft, IconWeight::Fill) => "icons/fill/caret-left-fill.svg",
            (IconName::AltArrowRight, IconWeight::Regular) => "icons/regular/caret-right.svg",
            (IconName::AltArrowRight, IconWeight::Fill) => "icons/fill/caret-right-fill.svg",
            (IconName::Archive, IconWeight::Regular) => "icons/regular/archive.svg",
            (IconName::Archive, IconWeight::Fill) => "icons/fill/archive-fill.svg",
            (IconName::ArchiveUp, IconWeight::Regular) => "icons/regular/box-arrow-up.svg",
            (IconName::ArchiveUp, IconWeight::Fill) => "icons/fill/box-arrow-up-fill.svg",
            (IconName::ArrowDown, IconWeight::Regular) => "icons/regular/arrow-down.svg",
            (IconName::ArrowDown, IconWeight::Fill) => "icons/fill/arrow-down-fill.svg",
            (IconName::ArrowLeft, IconWeight::Regular) => "icons/regular/arrow-left.svg",
            (IconName::ArrowLeft, IconWeight::Fill) => "icons/fill/arrow-left-fill.svg",
            (IconName::ArrowRight, IconWeight::Regular) => "icons/regular/arrow-right.svg",
            (IconName::ArrowRight, IconWeight::Fill) => "icons/fill/arrow-right-fill.svg",
            (IconName::ArrowUp, IconWeight::Regular) => "icons/regular/arrow-up.svg",
            (IconName::ArrowUp, IconWeight::Fill) => "icons/fill/arrow-up-fill.svg",
            (IconName::Browser, IconWeight::Regular) => "icons/regular/browser.svg",
            (IconName::Browser, IconWeight::Fill) => "icons/fill/browser-fill.svg",
            (IconName::Calendar, IconWeight::Regular) => "icons/regular/calendar.svg",
            (IconName::Calendar, IconWeight::Fill) => "icons/fill/calendar-fill.svg",
            (IconName::CalendarDots, IconWeight::Regular) => "icons/regular/calendar-dots.svg",
            (IconName::CalendarDots, IconWeight::Fill) => "icons/fill/calendar-dots-fill.svg",
            (IconName::Chat, IconWeight::Regular) => "icons/regular/chat-circle-text.svg",
            (IconName::Chat, IconWeight::Fill) => "icons/fill/chat-circle-text-fill.svg",
            (IconName::Check, IconWeight::Regular) => "icons/regular/check.svg",
            (IconName::Check, IconWeight::Fill) => "icons/fill/check-fill.svg",
            (IconName::CheckboxChecked, IconWeight::Regular) => "icons/regular/check-square.svg",
            (IconName::CheckboxChecked, IconWeight::Fill) => "icons/fill/check-square-fill.svg",
            (IconName::CheckboxEmpty, IconWeight::Regular) => "icons/regular/square.svg",
            (IconName::CheckboxEmpty, IconWeight::Fill) => "icons/fill/square-fill.svg",
            (IconName::CheckCircle, IconWeight::Regular) => "icons/regular/check-circle.svg",
            (IconName::CheckCircle, IconWeight::Fill) => "icons/fill/check-circle-fill.svg",
            (IconName::Checklist, IconWeight::Regular) => "icons/regular/list-checks.svg",
            (IconName::Checklist, IconWeight::Fill) => "icons/fill/list-checks-fill.svg",
            (IconName::ClockCountdown, IconWeight::Regular) => "icons/regular/clock-countdown.svg",
            (IconName::ClockCountdown, IconWeight::Fill) => "icons/fill/clock-countdown-fill.svg",
            (IconName::Close, IconWeight::Regular) => "icons/regular/x.svg",
            (IconName::Close, IconWeight::Fill) => "icons/fill/x-fill.svg",
            (IconName::CloseCircle, IconWeight::Regular) => "icons/regular/x-circle.svg",
            (IconName::CloseCircle, IconWeight::Fill) => "icons/fill/x-circle-fill.svg",
            (IconName::Command, IconWeight::Regular) => "icons/regular/command.svg",
            (IconName::Command, IconWeight::Fill) => "icons/fill/command-fill.svg",
            (IconName::Copy, IconWeight::Regular) => "icons/regular/copy.svg",
            (IconName::Copy, IconWeight::Fill) => "icons/fill/copy-fill.svg",
            (IconName::CornersIn, IconWeight::Regular) => "icons/regular/corners-in.svg",
            (IconName::CornersIn, IconWeight::Fill) => "icons/fill/corners-in-fill.svg",
            (IconName::Danger, IconWeight::Regular) => "icons/regular/warning.svg",
            (IconName::Danger, IconWeight::Fill) => "icons/fill/warning-fill.svg",
            (IconName::Document, IconWeight::Regular) => "icons/regular/file-text.svg",
            (IconName::Document, IconWeight::Fill) => "icons/fill/file-text-fill.svg",
            (IconName::DocumentAdd, IconWeight::Regular) => "icons/regular/file-plus.svg",
            (IconName::DocumentAdd, IconWeight::Fill) => "icons/fill/file-plus-fill.svg",
            (IconName::DoubleArrowLeft, IconWeight::Regular) => {
                "icons/regular/caret-double-left.svg"
            }
            (IconName::DoubleArrowLeft, IconWeight::Fill) => {
                "icons/fill/caret-double-left-fill.svg"
            }
            (IconName::DoubleArrowRight, IconWeight::Regular) => {
                "icons/regular/caret-double-right.svg"
            }
            (IconName::DoubleArrowRight, IconWeight::Fill) => {
                "icons/fill/caret-double-right-fill.svg"
            }
            (IconName::DragHandle, IconWeight::Regular) => "icons/regular/dots-six-vertical.svg",
            (IconName::DragHandle, IconWeight::Fill) => "icons/fill/dots-six-vertical-fill.svg",
            (IconName::ExternalLink, IconWeight::Regular) => "icons/regular/arrow-square-out.svg",
            (IconName::ExternalLink, IconWeight::Fill) => "icons/fill/arrow-square-out-fill.svg",
            (IconName::Filter, IconWeight::Regular) => "icons/regular/funnel-simple.svg",
            (IconName::Filter, IconWeight::Fill) => "icons/fill/funnel-simple-fill.svg",
            (IconName::Folder, IconWeight::Regular) => "icons/regular/folder.svg",
            (IconName::Folder, IconWeight::Fill) => "icons/fill/folder-fill.svg",
            (IconName::Forbidden, IconWeight::Regular) => "icons/regular/prohibit.svg",
            (IconName::Forbidden, IconWeight::Fill) => "icons/fill/prohibit-fill.svg",
            (IconName::FolderWithFiles, IconWeight::Regular) => "icons/regular/folders.svg",
            (IconName::FolderWithFiles, IconWeight::Fill) => "icons/fill/folders-fill.svg",
            (IconName::GitBranch, IconWeight::Regular) => "icons/regular/git-branch.svg",
            (IconName::GitBranch, IconWeight::Fill) => "icons/fill/git-branch-fill.svg",
            (IconName::GitDiff, IconWeight::Regular) => "icons/regular/git-diff.svg",
            (IconName::GitDiff, IconWeight::Fill) => "icons/fill/git-diff-fill.svg",
            (IconName::Global, IconWeight::Regular) => "icons/regular/globe.svg",
            (IconName::Global, IconWeight::Fill) => "icons/fill/globe-fill.svg",
            (IconName::Graph, IconWeight::Regular) => "icons/regular/graph.svg",
            (IconName::Graph, IconWeight::Fill) => "icons/fill/graph-fill.svg",
            (IconName::Home, IconWeight::Regular) => "icons/regular/house.svg",
            (IconName::Home, IconWeight::Fill) => "icons/fill/house-fill.svg",
            (IconName::Image, IconWeight::Regular) => "icons/regular/image.svg",
            (IconName::Image, IconWeight::Fill) => "icons/fill/image-fill.svg",
            (IconName::Info, IconWeight::Regular) => "icons/regular/info.svg",
            (IconName::Info, IconWeight::Fill) => "icons/fill/info-fill.svg",
            (IconName::Key, IconWeight::Regular) => "icons/regular/key.svg",
            (IconName::Key, IconWeight::Fill) => "icons/fill/key-fill.svg",
            (IconName::Keyboard, IconWeight::Regular) => "icons/regular/keyboard.svg",
            (IconName::Keyboard, IconWeight::Fill) => "icons/fill/keyboard-fill.svg",
            (IconName::Laptop, IconWeight::Regular) => "icons/regular/laptop.svg",
            (IconName::Laptop, IconWeight::Fill) => "icons/fill/laptop-fill.svg",
            (IconName::List, IconWeight::Regular) => "icons/regular/list.svg",
            (IconName::List, IconWeight::Fill) => "icons/fill/list-fill.svg",
            (IconName::Logout, IconWeight::Regular) => "icons/regular/sign-out.svg",
            (IconName::Logout, IconWeight::Fill) => "icons/fill/sign-out-fill.svg",
            (IconName::Magnifier, IconWeight::Regular) => "icons/regular/magnifying-glass.svg",
            (IconName::Magnifier, IconWeight::Fill) => "icons/fill/magnifying-glass-fill.svg",
            (IconName::Minus, IconWeight::Regular) => "icons/regular/minus.svg",
            (IconName::Minus, IconWeight::Fill) => "icons/fill/minus-fill.svg",
            (IconName::Monitor, IconWeight::Regular) => "icons/regular/monitor.svg",
            (IconName::Monitor, IconWeight::Fill) => "icons/fill/monitor-fill.svg",
            (IconName::MoreHorizontal, IconWeight::Regular) => "icons/regular/dots-three.svg",
            (IconName::MoreHorizontal, IconWeight::Fill) => "icons/fill/dots-three-fill.svg",
            (IconName::Notebook, IconWeight::Regular) => "icons/regular/notebook.svg",
            (IconName::Notebook, IconWeight::Fill) => "icons/fill/notebook-fill.svg",
            (IconName::Paperclip, IconWeight::Regular) => "icons/regular/paperclip.svg",
            (IconName::Paperclip, IconWeight::Fill) => "icons/fill/paperclip-fill.svg",
            (IconName::Pause, IconWeight::Regular) => "icons/regular/pause.svg",
            (IconName::Pause, IconWeight::Fill) => "icons/fill/pause-fill.svg",
            (IconName::Pen, IconWeight::Regular) => "icons/regular/pencil-simple.svg",
            (IconName::Pen, IconWeight::Fill) => "icons/fill/pencil-simple-fill.svg",
            (IconName::PenNew, IconWeight::Regular) => "icons/regular/note-pencil.svg",
            (IconName::PenNew, IconWeight::Fill) => "icons/fill/note-pencil-fill.svg",
            (IconName::Play, IconWeight::Regular) => "icons/regular/play.svg",
            (IconName::Play, IconWeight::Fill) => "icons/fill/play-fill.svg",
            (IconName::Plus, IconWeight::Regular) => "icons/regular/plus.svg",
            (IconName::Plus, IconWeight::Fill) => "icons/fill/plus-fill.svg",
            (IconName::Refresh, IconWeight::Regular) => "icons/regular/arrow-clockwise.svg",
            (IconName::Refresh, IconWeight::Fill) => "icons/fill/arrow-clockwise-fill.svg",
            (IconName::Restart, IconWeight::Regular) => {
                "icons/regular/arrows-counter-clockwise.svg"
            }
            (IconName::Restart, IconWeight::Fill) => "icons/fill/arrows-counter-clockwise-fill.svg",
            (IconName::Return, IconWeight::Regular) => "icons/regular/arrow-bend-up-left.svg",
            (IconName::Return, IconWeight::Fill) => "icons/fill/arrow-bend-up-left-fill.svg",
            (IconName::Settings, IconWeight::Regular) => "icons/regular/gear-six.svg",
            (IconName::Settings, IconWeight::Fill) => "icons/fill/gear-six-fill.svg",
            (IconName::Sidebar, IconWeight::Regular) => "icons/regular/sidebar.svg",
            (IconName::Sidebar, IconWeight::Fill) => "icons/fill/sidebar-fill.svg",
            (IconName::SidebarLeft, IconWeight::Regular) => "icons/regular/sidebar-simple.svg",
            (IconName::SidebarLeft, IconWeight::Fill) => "icons/fill/sidebar-simple-fill.svg",
            (IconName::Smartphone, IconWeight::Regular) => "icons/regular/device-mobile.svg",
            (IconName::Smartphone, IconWeight::Fill) => "icons/fill/device-mobile-fill.svg",
            (IconName::SortVertical, IconWeight::Regular) => "icons/regular/arrows-down-up.svg",
            (IconName::SortVertical, IconWeight::Fill) => "icons/fill/arrows-down-up-fill.svg",
            (IconName::Sparkle, IconWeight::Regular) => "icons/regular/sparkle.svg",
            (IconName::Sparkle, IconWeight::Fill) => "icons/fill/sparkle-fill.svg",
            (IconName::Spinner, IconWeight::Regular) => "icons/regular/spinner-gap.svg",
            (IconName::Spinner, IconWeight::Fill) => "icons/fill/spinner-gap-fill.svg",
            (IconName::Star, IconWeight::Regular) => "icons/regular/star.svg",
            (IconName::Star, IconWeight::Fill) => "icons/fill/star-fill.svg",
            (IconName::SoundWave, IconWeight::Regular) => "icons/regular/waveform.svg",
            (IconName::SoundWave, IconWeight::Fill) => "icons/fill/waveform-fill.svg",
            (IconName::Stop, IconWeight::Regular) => "icons/regular/stop.svg",
            (IconName::Stop, IconWeight::Fill) => "icons/fill/stop-fill.svg",
            (IconName::Terminal, IconWeight::Regular) => "icons/regular/terminal-window.svg",
            (IconName::Terminal, IconWeight::Fill) => "icons/fill/terminal-window-fill.svg",
            (IconName::Trash, IconWeight::Regular) => "icons/regular/trash.svg",
            (IconName::Trash, IconWeight::Fill) => "icons/fill/trash-fill.svg",
            (IconName::Tuning, IconWeight::Regular) => "icons/regular/sliders-horizontal.svg",
            (IconName::Tuning, IconWeight::Fill) => "icons/fill/sliders-horizontal-fill.svg",
            (IconName::Video, IconWeight::Regular) => "icons/regular/video-camera.svg",
            (IconName::Video, IconWeight::Fill) => "icons/fill/video-camera-fill.svg",
            (IconName::Widget, IconWeight::Regular) => "icons/regular/squares-four.svg",
            (IconName::Widget, IconWeight::Fill) => "icons/fill/squares-four-fill.svg",
        }
    }

    /// A glyph record. Use icon_bundle! to evaluate selection at compile time.
    pub const fn asset(self) -> crate::IconAsset {
        crate::IconAsset {
            path: self.path(),
            bytes: match (self.name, self.weight) {
                (IconName::AddCircle, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/plus-circle.svg").as_slice()
                }
                (IconName::AddCircle, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/plus-circle-fill.svg").as_slice()
                }
                (IconName::AltArrowDown, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/caret-down.svg").as_slice()
                }
                (IconName::AltArrowDown, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/caret-down-fill.svg").as_slice()
                }
                (IconName::AltArrowLeft, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/caret-left.svg").as_slice()
                }
                (IconName::AltArrowLeft, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/caret-left-fill.svg").as_slice()
                }
                (IconName::AltArrowRight, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/caret-right.svg").as_slice()
                }
                (IconName::AltArrowRight, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/caret-right-fill.svg").as_slice()
                }
                (IconName::Archive, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/archive.svg").as_slice()
                }
                (IconName::Archive, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/archive-fill.svg").as_slice()
                }
                (IconName::ArchiveUp, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/box-arrow-up.svg").as_slice()
                }
                (IconName::ArchiveUp, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/box-arrow-up-fill.svg").as_slice()
                }
                (IconName::ArrowDown, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-down.svg").as_slice()
                }
                (IconName::ArrowDown, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-down-fill.svg").as_slice()
                }
                (IconName::ArrowLeft, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-left.svg").as_slice()
                }
                (IconName::ArrowLeft, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-left-fill.svg").as_slice()
                }
                (IconName::ArrowRight, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-right.svg").as_slice()
                }
                (IconName::ArrowRight, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-right-fill.svg").as_slice()
                }
                (IconName::ArrowUp, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-up.svg").as_slice()
                }
                (IconName::ArrowUp, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-up-fill.svg").as_slice()
                }
                (IconName::Browser, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/browser.svg").as_slice()
                }
                (IconName::Browser, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/browser-fill.svg").as_slice()
                }
                (IconName::Calendar, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/calendar.svg").as_slice()
                }
                (IconName::Calendar, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/calendar-fill.svg").as_slice()
                }
                (IconName::CalendarDots, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/calendar-dots.svg").as_slice()
                }
                (IconName::CalendarDots, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/calendar-dots-fill.svg").as_slice()
                }
                (IconName::Chat, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/chat-circle-text.svg").as_slice()
                }
                (IconName::Chat, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/chat-circle-text-fill.svg").as_slice()
                }
                (IconName::Check, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/check.svg").as_slice()
                }
                (IconName::Check, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/check-fill.svg").as_slice()
                }
                (IconName::CheckboxChecked, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/check-square.svg").as_slice()
                }
                (IconName::CheckboxChecked, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/check-square-fill.svg").as_slice()
                }
                (IconName::CheckboxEmpty, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/square.svg").as_slice()
                }
                (IconName::CheckboxEmpty, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/square-fill.svg").as_slice()
                }
                (IconName::CheckCircle, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/check-circle.svg").as_slice()
                }
                (IconName::CheckCircle, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/check-circle-fill.svg").as_slice()
                }
                (IconName::Checklist, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/list-checks.svg").as_slice()
                }
                (IconName::Checklist, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/list-checks-fill.svg").as_slice()
                }
                (IconName::ClockCountdown, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/clock-countdown.svg").as_slice()
                }
                (IconName::ClockCountdown, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/clock-countdown-fill.svg").as_slice()
                }
                (IconName::Close, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/x.svg").as_slice()
                }
                (IconName::Close, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/x-fill.svg").as_slice()
                }
                (IconName::CloseCircle, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/x-circle.svg").as_slice()
                }
                (IconName::CloseCircle, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/x-circle-fill.svg").as_slice()
                }
                (IconName::Command, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/command.svg").as_slice()
                }
                (IconName::Command, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/command-fill.svg").as_slice()
                }
                (IconName::Copy, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/copy.svg").as_slice()
                }
                (IconName::Copy, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/copy-fill.svg").as_slice()
                }
                (IconName::CornersIn, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/corners-in.svg").as_slice()
                }
                (IconName::CornersIn, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/corners-in-fill.svg").as_slice()
                }
                (IconName::Danger, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/warning.svg").as_slice()
                }
                (IconName::Danger, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/warning-fill.svg").as_slice()
                }
                (IconName::Document, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/file-text.svg").as_slice()
                }
                (IconName::Document, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/file-text-fill.svg").as_slice()
                }
                (IconName::DocumentAdd, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/file-plus.svg").as_slice()
                }
                (IconName::DocumentAdd, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/file-plus-fill.svg").as_slice()
                }
                (IconName::DoubleArrowLeft, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/caret-double-left.svg").as_slice()
                }
                (IconName::DoubleArrowLeft, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/caret-double-left-fill.svg").as_slice()
                }
                (IconName::DoubleArrowRight, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/caret-double-right.svg").as_slice()
                }
                (IconName::DoubleArrowRight, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/caret-double-right-fill.svg").as_slice()
                }
                (IconName::DragHandle, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/dots-six-vertical.svg").as_slice()
                }
                (IconName::DragHandle, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/dots-six-vertical-fill.svg").as_slice()
                }
                (IconName::ExternalLink, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-square-out.svg").as_slice()
                }
                (IconName::ExternalLink, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-square-out-fill.svg").as_slice()
                }
                (IconName::Filter, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/funnel-simple.svg").as_slice()
                }
                (IconName::Filter, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/funnel-simple-fill.svg").as_slice()
                }
                (IconName::Folder, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/folder.svg").as_slice()
                }
                (IconName::Folder, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/folder-fill.svg").as_slice()
                }
                (IconName::Forbidden, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/prohibit.svg").as_slice()
                }
                (IconName::Forbidden, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/prohibit-fill.svg").as_slice()
                }
                (IconName::FolderWithFiles, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/folders.svg").as_slice()
                }
                (IconName::FolderWithFiles, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/folders-fill.svg").as_slice()
                }
                (IconName::GitBranch, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/git-branch.svg").as_slice()
                }
                (IconName::GitBranch, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/git-branch-fill.svg").as_slice()
                }
                (IconName::GitDiff, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/git-diff.svg").as_slice()
                }
                (IconName::GitDiff, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/git-diff-fill.svg").as_slice()
                }
                (IconName::Global, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/globe.svg").as_slice()
                }
                (IconName::Global, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/globe-fill.svg").as_slice()
                }
                (IconName::Graph, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/graph.svg").as_slice()
                }
                (IconName::Graph, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/graph-fill.svg").as_slice()
                }
                (IconName::Home, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/house.svg").as_slice()
                }
                (IconName::Home, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/house-fill.svg").as_slice()
                }
                (IconName::Image, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/image.svg").as_slice()
                }
                (IconName::Image, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/image-fill.svg").as_slice()
                }
                (IconName::Info, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/info.svg").as_slice()
                }
                (IconName::Info, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/info-fill.svg").as_slice()
                }
                (IconName::Key, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/key.svg").as_slice()
                }
                (IconName::Key, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/key-fill.svg").as_slice()
                }
                (IconName::Keyboard, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/keyboard.svg").as_slice()
                }
                (IconName::Keyboard, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/keyboard-fill.svg").as_slice()
                }
                (IconName::Laptop, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/laptop.svg").as_slice()
                }
                (IconName::Laptop, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/laptop-fill.svg").as_slice()
                }
                (IconName::List, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/list.svg").as_slice()
                }
                (IconName::List, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/list-fill.svg").as_slice()
                }
                (IconName::Logout, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/sign-out.svg").as_slice()
                }
                (IconName::Logout, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/sign-out-fill.svg").as_slice()
                }
                (IconName::Magnifier, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/magnifying-glass.svg").as_slice()
                }
                (IconName::Magnifier, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/magnifying-glass-fill.svg").as_slice()
                }
                (IconName::Minus, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/minus.svg").as_slice()
                }
                (IconName::Minus, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/minus-fill.svg").as_slice()
                }
                (IconName::Monitor, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/monitor.svg").as_slice()
                }
                (IconName::Monitor, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/monitor-fill.svg").as_slice()
                }
                (IconName::MoreHorizontal, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/dots-three.svg").as_slice()
                }
                (IconName::MoreHorizontal, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/dots-three-fill.svg").as_slice()
                }
                (IconName::Notebook, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/notebook.svg").as_slice()
                }
                (IconName::Notebook, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/notebook-fill.svg").as_slice()
                }
                (IconName::Paperclip, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/paperclip.svg").as_slice()
                }
                (IconName::Paperclip, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/paperclip-fill.svg").as_slice()
                }
                (IconName::Pause, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/pause.svg").as_slice()
                }
                (IconName::Pause, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/pause-fill.svg").as_slice()
                }
                (IconName::Pen, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/pencil-simple.svg").as_slice()
                }
                (IconName::Pen, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/pencil-simple-fill.svg").as_slice()
                }
                (IconName::PenNew, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/note-pencil.svg").as_slice()
                }
                (IconName::PenNew, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/note-pencil-fill.svg").as_slice()
                }
                (IconName::Play, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/play.svg").as_slice()
                }
                (IconName::Play, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/play-fill.svg").as_slice()
                }
                (IconName::Plus, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/plus.svg").as_slice()
                }
                (IconName::Plus, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/plus-fill.svg").as_slice()
                }
                (IconName::Refresh, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-clockwise.svg").as_slice()
                }
                (IconName::Refresh, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-clockwise-fill.svg").as_slice()
                }
                (IconName::Restart, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrows-counter-clockwise.svg")
                        .as_slice()
                }
                (IconName::Restart, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrows-counter-clockwise-fill.svg")
                        .as_slice()
                }
                (IconName::Return, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrow-bend-up-left.svg").as_slice()
                }
                (IconName::Return, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrow-bend-up-left-fill.svg").as_slice()
                }
                (IconName::Settings, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/gear-six.svg").as_slice()
                }
                (IconName::Settings, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/gear-six-fill.svg").as_slice()
                }
                (IconName::Sidebar, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/sidebar.svg").as_slice()
                }
                (IconName::Sidebar, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/sidebar-fill.svg").as_slice()
                }
                (IconName::SidebarLeft, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/sidebar-simple.svg").as_slice()
                }
                (IconName::SidebarLeft, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/sidebar-simple-fill.svg").as_slice()
                }
                (IconName::Smartphone, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/device-mobile.svg").as_slice()
                }
                (IconName::Smartphone, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/device-mobile-fill.svg").as_slice()
                }
                (IconName::SortVertical, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/arrows-down-up.svg").as_slice()
                }
                (IconName::SortVertical, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/arrows-down-up-fill.svg").as_slice()
                }
                (IconName::Sparkle, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/sparkle.svg").as_slice()
                }
                (IconName::Sparkle, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/sparkle-fill.svg").as_slice()
                }
                (IconName::Spinner, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/spinner-gap.svg").as_slice()
                }
                (IconName::Spinner, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/spinner-gap-fill.svg").as_slice()
                }
                (IconName::Star, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/star.svg").as_slice()
                }
                (IconName::Star, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/star-fill.svg").as_slice()
                }
                (IconName::SoundWave, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/waveform.svg").as_slice()
                }
                (IconName::SoundWave, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/waveform-fill.svg").as_slice()
                }
                (IconName::Stop, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/stop.svg").as_slice()
                }
                (IconName::Stop, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/stop-fill.svg").as_slice()
                }
                (IconName::Terminal, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/terminal-window.svg").as_slice()
                }
                (IconName::Terminal, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/terminal-window-fill.svg").as_slice()
                }
                (IconName::Trash, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/trash.svg").as_slice()
                }
                (IconName::Trash, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/trash-fill.svg").as_slice()
                }
                (IconName::Tuning, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/sliders-horizontal.svg").as_slice()
                }
                (IconName::Tuning, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/sliders-horizontal-fill.svg").as_slice()
                }
                (IconName::Video, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/video-camera.svg").as_slice()
                }
                (IconName::Video, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/video-camera-fill.svg").as_slice()
                }
                (IconName::Widget, IconWeight::Regular) => {
                    include_bytes!("../assets/icons/regular/squares-four.svg").as_slice()
                }
                (IconName::Widget, IconWeight::Fill) => {
                    include_bytes!("../assets/icons/fill/squares-four-fill.svg").as_slice()
                }
            },
        }
    }
}

impl std::fmt::Debug for Icon {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.weight {
            IconWeight::Regular => self.name.fmt(formatter),
            weight => write!(formatter, "{:?}.{:?}", self.name, weight),
        }
    }
}

pub(crate) const ALL_PATHS: &[&str] = &[
    "icons/regular/plus-circle.svg",
    "icons/fill/plus-circle-fill.svg",
    "icons/regular/caret-down.svg",
    "icons/fill/caret-down-fill.svg",
    "icons/regular/caret-left.svg",
    "icons/fill/caret-left-fill.svg",
    "icons/regular/caret-right.svg",
    "icons/fill/caret-right-fill.svg",
    "icons/regular/archive.svg",
    "icons/fill/archive-fill.svg",
    "icons/regular/box-arrow-up.svg",
    "icons/fill/box-arrow-up-fill.svg",
    "icons/regular/arrow-down.svg",
    "icons/fill/arrow-down-fill.svg",
    "icons/regular/arrow-left.svg",
    "icons/fill/arrow-left-fill.svg",
    "icons/regular/arrow-right.svg",
    "icons/fill/arrow-right-fill.svg",
    "icons/regular/arrow-up.svg",
    "icons/fill/arrow-up-fill.svg",
    "icons/regular/browser.svg",
    "icons/fill/browser-fill.svg",
    "icons/regular/calendar.svg",
    "icons/fill/calendar-fill.svg",
    "icons/regular/calendar-dots.svg",
    "icons/fill/calendar-dots-fill.svg",
    "icons/regular/chat-circle-text.svg",
    "icons/fill/chat-circle-text-fill.svg",
    "icons/regular/check.svg",
    "icons/fill/check-fill.svg",
    "icons/regular/check-square.svg",
    "icons/fill/check-square-fill.svg",
    "icons/regular/square.svg",
    "icons/fill/square-fill.svg",
    "icons/regular/check-circle.svg",
    "icons/fill/check-circle-fill.svg",
    "icons/regular/list-checks.svg",
    "icons/fill/list-checks-fill.svg",
    "icons/regular/clock-countdown.svg",
    "icons/fill/clock-countdown-fill.svg",
    "icons/regular/x.svg",
    "icons/fill/x-fill.svg",
    "icons/regular/x-circle.svg",
    "icons/fill/x-circle-fill.svg",
    "icons/regular/command.svg",
    "icons/fill/command-fill.svg",
    "icons/regular/copy.svg",
    "icons/fill/copy-fill.svg",
    "icons/regular/corners-in.svg",
    "icons/fill/corners-in-fill.svg",
    "icons/regular/warning.svg",
    "icons/fill/warning-fill.svg",
    "icons/regular/file-text.svg",
    "icons/fill/file-text-fill.svg",
    "icons/regular/file-plus.svg",
    "icons/fill/file-plus-fill.svg",
    "icons/regular/caret-double-left.svg",
    "icons/fill/caret-double-left-fill.svg",
    "icons/regular/caret-double-right.svg",
    "icons/fill/caret-double-right-fill.svg",
    "icons/regular/dots-six-vertical.svg",
    "icons/fill/dots-six-vertical-fill.svg",
    "icons/regular/arrow-square-out.svg",
    "icons/fill/arrow-square-out-fill.svg",
    "icons/regular/funnel-simple.svg",
    "icons/fill/funnel-simple-fill.svg",
    "icons/regular/folder.svg",
    "icons/fill/folder-fill.svg",
    "icons/regular/prohibit.svg",
    "icons/fill/prohibit-fill.svg",
    "icons/regular/folders.svg",
    "icons/fill/folders-fill.svg",
    "icons/regular/git-branch.svg",
    "icons/fill/git-branch-fill.svg",
    "icons/regular/git-diff.svg",
    "icons/fill/git-diff-fill.svg",
    "icons/regular/globe.svg",
    "icons/fill/globe-fill.svg",
    "icons/regular/graph.svg",
    "icons/fill/graph-fill.svg",
    "icons/regular/house.svg",
    "icons/fill/house-fill.svg",
    "icons/regular/image.svg",
    "icons/fill/image-fill.svg",
    "icons/regular/info.svg",
    "icons/fill/info-fill.svg",
    "icons/regular/key.svg",
    "icons/fill/key-fill.svg",
    "icons/regular/keyboard.svg",
    "icons/fill/keyboard-fill.svg",
    "icons/regular/laptop.svg",
    "icons/fill/laptop-fill.svg",
    "icons/regular/list.svg",
    "icons/fill/list-fill.svg",
    "icons/regular/sign-out.svg",
    "icons/fill/sign-out-fill.svg",
    "icons/regular/magnifying-glass.svg",
    "icons/fill/magnifying-glass-fill.svg",
    "icons/regular/minus.svg",
    "icons/fill/minus-fill.svg",
    "icons/regular/monitor.svg",
    "icons/fill/monitor-fill.svg",
    "icons/regular/dots-three.svg",
    "icons/fill/dots-three-fill.svg",
    "icons/regular/notebook.svg",
    "icons/fill/notebook-fill.svg",
    "icons/regular/paperclip.svg",
    "icons/fill/paperclip-fill.svg",
    "icons/regular/pause.svg",
    "icons/fill/pause-fill.svg",
    "icons/regular/pencil-simple.svg",
    "icons/fill/pencil-simple-fill.svg",
    "icons/regular/note-pencil.svg",
    "icons/fill/note-pencil-fill.svg",
    "icons/regular/play.svg",
    "icons/fill/play-fill.svg",
    "icons/regular/plus.svg",
    "icons/fill/plus-fill.svg",
    "icons/regular/arrow-clockwise.svg",
    "icons/fill/arrow-clockwise-fill.svg",
    "icons/regular/arrows-counter-clockwise.svg",
    "icons/fill/arrows-counter-clockwise-fill.svg",
    "icons/regular/arrow-bend-up-left.svg",
    "icons/fill/arrow-bend-up-left-fill.svg",
    "icons/regular/gear-six.svg",
    "icons/fill/gear-six-fill.svg",
    "icons/regular/sidebar.svg",
    "icons/fill/sidebar-fill.svg",
    "icons/regular/sidebar-simple.svg",
    "icons/fill/sidebar-simple-fill.svg",
    "icons/regular/device-mobile.svg",
    "icons/fill/device-mobile-fill.svg",
    "icons/regular/arrows-down-up.svg",
    "icons/fill/arrows-down-up-fill.svg",
    "icons/regular/sparkle.svg",
    "icons/fill/sparkle-fill.svg",
    "icons/regular/spinner-gap.svg",
    "icons/fill/spinner-gap-fill.svg",
    "icons/regular/star.svg",
    "icons/fill/star-fill.svg",
    "icons/regular/waveform.svg",
    "icons/fill/waveform-fill.svg",
    "icons/regular/stop.svg",
    "icons/fill/stop-fill.svg",
    "icons/regular/terminal-window.svg",
    "icons/fill/terminal-window-fill.svg",
    "icons/regular/trash.svg",
    "icons/fill/trash-fill.svg",
    "icons/regular/sliders-horizontal.svg",
    "icons/fill/sliders-horizontal-fill.svg",
    "icons/regular/video-camera.svg",
    "icons/fill/video-camera-fill.svg",
    "icons/regular/squares-four.svg",
    "icons/fill/squares-four-fill.svg",
];

pub(crate) fn load(path: &str) -> Option<Cow<'static, [u8]>> {
    match path {
        "icons/regular/plus-circle.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/plus-circle.svg").as_slice(),
        )),
        "icons/fill/plus-circle-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/plus-circle-fill.svg").as_slice(),
        )),
        "icons/regular/caret-down.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/caret-down.svg").as_slice(),
        )),
        "icons/fill/caret-down-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/caret-down-fill.svg").as_slice(),
        )),
        "icons/regular/caret-left.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/caret-left.svg").as_slice(),
        )),
        "icons/fill/caret-left-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/caret-left-fill.svg").as_slice(),
        )),
        "icons/regular/caret-right.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/caret-right.svg").as_slice(),
        )),
        "icons/fill/caret-right-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/caret-right-fill.svg").as_slice(),
        )),
        "icons/regular/archive.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/archive.svg").as_slice(),
        )),
        "icons/fill/archive-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/archive-fill.svg").as_slice(),
        )),
        "icons/regular/box-arrow-up.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/box-arrow-up.svg").as_slice(),
        )),
        "icons/fill/box-arrow-up-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/box-arrow-up-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-down.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-down.svg").as_slice(),
        )),
        "icons/fill/arrow-down-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-down-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-left.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-left.svg").as_slice(),
        )),
        "icons/fill/arrow-left-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-left-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-right.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-right.svg").as_slice(),
        )),
        "icons/fill/arrow-right-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-right-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-up.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-up.svg").as_slice(),
        )),
        "icons/fill/arrow-up-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-up-fill.svg").as_slice(),
        )),
        "icons/regular/browser.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/browser.svg").as_slice(),
        )),
        "icons/fill/browser-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/browser-fill.svg").as_slice(),
        )),
        "icons/regular/calendar.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/calendar.svg").as_slice(),
        )),
        "icons/fill/calendar-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/calendar-fill.svg").as_slice(),
        )),
        "icons/regular/calendar-dots.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/calendar-dots.svg").as_slice(),
        )),
        "icons/fill/calendar-dots-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/calendar-dots-fill.svg").as_slice(),
        )),
        "icons/regular/chat-circle-text.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/chat-circle-text.svg").as_slice(),
        )),
        "icons/fill/chat-circle-text-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/chat-circle-text-fill.svg").as_slice(),
        )),
        "icons/regular/check.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/check.svg").as_slice(),
        )),
        "icons/fill/check-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/check-fill.svg").as_slice(),
        )),
        "icons/regular/check-square.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/check-square.svg").as_slice(),
        )),
        "icons/fill/check-square-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/check-square-fill.svg").as_slice(),
        )),
        "icons/regular/square.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/square.svg").as_slice(),
        )),
        "icons/fill/square-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/square-fill.svg").as_slice(),
        )),
        "icons/regular/check-circle.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/check-circle.svg").as_slice(),
        )),
        "icons/fill/check-circle-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/check-circle-fill.svg").as_slice(),
        )),
        "icons/regular/list-checks.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/list-checks.svg").as_slice(),
        )),
        "icons/fill/list-checks-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/list-checks-fill.svg").as_slice(),
        )),
        "icons/regular/clock-countdown.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/clock-countdown.svg").as_slice(),
        )),
        "icons/fill/clock-countdown-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/clock-countdown-fill.svg").as_slice(),
        )),
        "icons/regular/x.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/x.svg").as_slice(),
        )),
        "icons/fill/x-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/x-fill.svg").as_slice(),
        )),
        "icons/regular/x-circle.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/x-circle.svg").as_slice(),
        )),
        "icons/fill/x-circle-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/x-circle-fill.svg").as_slice(),
        )),
        "icons/regular/command.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/command.svg").as_slice(),
        )),
        "icons/fill/command-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/command-fill.svg").as_slice(),
        )),
        "icons/regular/copy.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/copy.svg").as_slice(),
        )),
        "icons/fill/copy-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/copy-fill.svg").as_slice(),
        )),
        "icons/regular/corners-in.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/corners-in.svg").as_slice(),
        )),
        "icons/fill/corners-in-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/corners-in-fill.svg").as_slice(),
        )),
        "icons/regular/warning.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/warning.svg").as_slice(),
        )),
        "icons/fill/warning-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/warning-fill.svg").as_slice(),
        )),
        "icons/regular/file-text.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/file-text.svg").as_slice(),
        )),
        "icons/fill/file-text-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/file-text-fill.svg").as_slice(),
        )),
        "icons/regular/file-plus.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/file-plus.svg").as_slice(),
        )),
        "icons/fill/file-plus-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/file-plus-fill.svg").as_slice(),
        )),
        "icons/regular/caret-double-left.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/caret-double-left.svg").as_slice(),
        )),
        "icons/fill/caret-double-left-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/caret-double-left-fill.svg").as_slice(),
        )),
        "icons/regular/caret-double-right.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/caret-double-right.svg").as_slice(),
        )),
        "icons/fill/caret-double-right-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/caret-double-right-fill.svg").as_slice(),
        )),
        "icons/regular/dots-six-vertical.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/dots-six-vertical.svg").as_slice(),
        )),
        "icons/fill/dots-six-vertical-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/dots-six-vertical-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-square-out.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-square-out.svg").as_slice(),
        )),
        "icons/fill/arrow-square-out-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-square-out-fill.svg").as_slice(),
        )),
        "icons/regular/funnel-simple.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/funnel-simple.svg").as_slice(),
        )),
        "icons/fill/funnel-simple-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/funnel-simple-fill.svg").as_slice(),
        )),
        "icons/regular/folder.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/folder.svg").as_slice(),
        )),
        "icons/fill/folder-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/folder-fill.svg").as_slice(),
        )),
        "icons/regular/prohibit.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/prohibit.svg").as_slice(),
        )),
        "icons/fill/prohibit-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/prohibit-fill.svg").as_slice(),
        )),
        "icons/regular/folders.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/folders.svg").as_slice(),
        )),
        "icons/fill/folders-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/folders-fill.svg").as_slice(),
        )),
        "icons/regular/git-branch.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/git-branch.svg").as_slice(),
        )),
        "icons/fill/git-branch-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/git-branch-fill.svg").as_slice(),
        )),
        "icons/regular/git-diff.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/git-diff.svg").as_slice(),
        )),
        "icons/fill/git-diff-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/git-diff-fill.svg").as_slice(),
        )),
        "icons/regular/globe.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/globe.svg").as_slice(),
        )),
        "icons/fill/globe-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/globe-fill.svg").as_slice(),
        )),
        "icons/regular/graph.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/graph.svg").as_slice(),
        )),
        "icons/fill/graph-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/graph-fill.svg").as_slice(),
        )),
        "icons/regular/house.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/house.svg").as_slice(),
        )),
        "icons/fill/house-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/house-fill.svg").as_slice(),
        )),
        "icons/regular/image.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/image.svg").as_slice(),
        )),
        "icons/fill/image-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/image-fill.svg").as_slice(),
        )),
        "icons/regular/info.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/info.svg").as_slice(),
        )),
        "icons/fill/info-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/info-fill.svg").as_slice(),
        )),
        "icons/regular/key.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/key.svg").as_slice(),
        )),
        "icons/fill/key-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/key-fill.svg").as_slice(),
        )),
        "icons/regular/keyboard.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/keyboard.svg").as_slice(),
        )),
        "icons/fill/keyboard-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/keyboard-fill.svg").as_slice(),
        )),
        "icons/regular/laptop.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/laptop.svg").as_slice(),
        )),
        "icons/fill/laptop-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/laptop-fill.svg").as_slice(),
        )),
        "icons/regular/list.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/list.svg").as_slice(),
        )),
        "icons/fill/list-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/list-fill.svg").as_slice(),
        )),
        "icons/regular/sign-out.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/sign-out.svg").as_slice(),
        )),
        "icons/fill/sign-out-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/sign-out-fill.svg").as_slice(),
        )),
        "icons/regular/magnifying-glass.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/magnifying-glass.svg").as_slice(),
        )),
        "icons/fill/magnifying-glass-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/magnifying-glass-fill.svg").as_slice(),
        )),
        "icons/regular/minus.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/minus.svg").as_slice(),
        )),
        "icons/fill/minus-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/minus-fill.svg").as_slice(),
        )),
        "icons/regular/monitor.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/monitor.svg").as_slice(),
        )),
        "icons/fill/monitor-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/monitor-fill.svg").as_slice(),
        )),
        "icons/regular/dots-three.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/dots-three.svg").as_slice(),
        )),
        "icons/fill/dots-three-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/dots-three-fill.svg").as_slice(),
        )),
        "icons/regular/notebook.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/notebook.svg").as_slice(),
        )),
        "icons/fill/notebook-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/notebook-fill.svg").as_slice(),
        )),
        "icons/regular/paperclip.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/paperclip.svg").as_slice(),
        )),
        "icons/fill/paperclip-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/paperclip-fill.svg").as_slice(),
        )),
        "icons/regular/pause.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/pause.svg").as_slice(),
        )),
        "icons/fill/pause-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/pause-fill.svg").as_slice(),
        )),
        "icons/regular/pencil-simple.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/pencil-simple.svg").as_slice(),
        )),
        "icons/fill/pencil-simple-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/pencil-simple-fill.svg").as_slice(),
        )),
        "icons/regular/note-pencil.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/note-pencil.svg").as_slice(),
        )),
        "icons/fill/note-pencil-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/note-pencil-fill.svg").as_slice(),
        )),
        "icons/regular/play.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/play.svg").as_slice(),
        )),
        "icons/fill/play-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/play-fill.svg").as_slice(),
        )),
        "icons/regular/plus.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/plus.svg").as_slice(),
        )),
        "icons/fill/plus-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/plus-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-clockwise.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-clockwise.svg").as_slice(),
        )),
        "icons/fill/arrow-clockwise-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-clockwise-fill.svg").as_slice(),
        )),
        "icons/regular/arrows-counter-clockwise.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrows-counter-clockwise.svg").as_slice(),
        )),
        "icons/fill/arrows-counter-clockwise-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrows-counter-clockwise-fill.svg").as_slice(),
        )),
        "icons/regular/arrow-bend-up-left.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrow-bend-up-left.svg").as_slice(),
        )),
        "icons/fill/arrow-bend-up-left-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrow-bend-up-left-fill.svg").as_slice(),
        )),
        "icons/regular/gear-six.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/gear-six.svg").as_slice(),
        )),
        "icons/fill/gear-six-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/gear-six-fill.svg").as_slice(),
        )),
        "icons/regular/sidebar.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/sidebar.svg").as_slice(),
        )),
        "icons/fill/sidebar-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/sidebar-fill.svg").as_slice(),
        )),
        "icons/regular/sidebar-simple.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/sidebar-simple.svg").as_slice(),
        )),
        "icons/fill/sidebar-simple-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/sidebar-simple-fill.svg").as_slice(),
        )),
        "icons/regular/device-mobile.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/device-mobile.svg").as_slice(),
        )),
        "icons/fill/device-mobile-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/device-mobile-fill.svg").as_slice(),
        )),
        "icons/regular/arrows-down-up.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/arrows-down-up.svg").as_slice(),
        )),
        "icons/fill/arrows-down-up-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/arrows-down-up-fill.svg").as_slice(),
        )),
        "icons/regular/sparkle.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/sparkle.svg").as_slice(),
        )),
        "icons/fill/sparkle-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/sparkle-fill.svg").as_slice(),
        )),
        "icons/regular/spinner-gap.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/spinner-gap.svg").as_slice(),
        )),
        "icons/fill/spinner-gap-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/spinner-gap-fill.svg").as_slice(),
        )),
        "icons/regular/star.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/star.svg").as_slice(),
        )),
        "icons/fill/star-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/star-fill.svg").as_slice(),
        )),
        "icons/regular/waveform.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/waveform.svg").as_slice(),
        )),
        "icons/fill/waveform-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/waveform-fill.svg").as_slice(),
        )),
        "icons/regular/stop.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/stop.svg").as_slice(),
        )),
        "icons/fill/stop-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/stop-fill.svg").as_slice(),
        )),
        "icons/regular/terminal-window.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/terminal-window.svg").as_slice(),
        )),
        "icons/fill/terminal-window-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/terminal-window-fill.svg").as_slice(),
        )),
        "icons/regular/trash.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/trash.svg").as_slice(),
        )),
        "icons/fill/trash-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/trash-fill.svg").as_slice(),
        )),
        "icons/regular/sliders-horizontal.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/sliders-horizontal.svg").as_slice(),
        )),
        "icons/fill/sliders-horizontal-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/sliders-horizontal-fill.svg").as_slice(),
        )),
        "icons/regular/video-camera.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/video-camera.svg").as_slice(),
        )),
        "icons/fill/video-camera-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/video-camera-fill.svg").as_slice(),
        )),
        "icons/regular/squares-four.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/regular/squares-four.svg").as_slice(),
        )),
        "icons/fill/squares-four-fill.svg" => Some(Cow::Borrowed(
            include_bytes!("../assets/icons/fill/squares-four-fill.svg").as_slice(),
        )),
        _ => None,
    }
}
