//! Complete built-in UI vocabulary, not automatic locale detection or number/date policy.
use super::{StringKey, Strings};

/// Complete, bundled translations of Kit-owned labels. Caller content is never
/// translated. Install `pack.strings()` with `cx.set_global`, then apply any
/// application-specific overrides through the existing [`Strings`] interface.
/// Number/date adapters, search matching and layout direction stay caller-owned.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TranslationPack {
    English,
    SimplifiedChinese,
}

impl TranslationPack {
    pub const ALL: &'static [Self] = &[Self::English, Self::SimplifiedChinese];

    pub const fn language_tag(self) -> &'static str {
        match self {
            Self::English => "en",
            Self::SimplifiedChinese => "zh-Hans",
        }
    }

    pub fn text(self, key: StringKey) -> &'static str {
        match self {
            Self::English => key.english(),
            Self::SimplifiedChinese => chinese(key),
        }
    }

    /// A fresh caller-owned catalogue; later overrides never mutate the pack.
    pub fn strings(self) -> Strings {
        let mut strings = Strings::new();
        if self != Self::English {
            for &key in StringKey::ALL {
                strings.set(key, self.text(key));
            }
        }
        strings
    }
}

// Exhaustiveness is intentional: adding a StringKey must update every built-in
// language rather than quietly producing a mixed-language interface.
fn chinese(key: StringKey) -> &'static str {
    use StringKey::*;
    match key {
        Copy => "复制",
        Dismiss => "关闭",
        TryAgain => "重试",
        Loading | TreeLoadingChildren => "加载中",
        Validating => "验证中…",
        LoadMore => "加载更多",
        LoadMoreLoading => "正在加载更多",
        LoadMoreEnd => "没有更多项目",
        MoreActions => "更多操作",
        Expand => "展开",
        Collapse => "折叠",
        SidebarItemWithBadge => "{0} · {1}",
        AttachmentReady | GameAbilityReady => "就绪",
        AttachmentQueued | AgentQueued | UploadQueued => "已排队",
        AttachmentTransferring => "传输中",
        AttachmentPaused => "传输已暂停",
        AttachmentProcessing => "处理中",
        AttachmentCancelled => "传输已取消",
        PasswordReveal => "显示密码",
        PasswordConceal => "隐藏密码",
        CalendarNoMonth => "没有可显示的月份",
        CalendarPreviousMonth => "上个月",
        CalendarNextMonth => "下个月",
        CalendarUnknownMonth => "无法确定要显示的月份",
        CalendarUnknownMonthDetail => "尚未选择日期，宿主未提供今天的日期，也未指定月份。",
        DateInputOpen => "打开日历",
        DateInputPlaceholder => "日期",
        RangeUnset => "尚未选择范围。",
        RangeIncomplete => "从 {0} 到尚未选择的结束日期。",
        RangeComplete => "从 {0} 到 {1}。",
        RangeInverted => "结束日期 {0} 早于开始日期 {1}。",
        RangeUncheckable => "宿主无法列出此范围内的日期，因此尚未检查其中任何一天。",
        RangeBlockedDay | PermissionCellName | AgentRunCanvasRelationLabel => "{0}：{1}",
        TimeHour => "时",
        TimeMinute => "分",
        TimeSecond => "秒",
        TimeMeridiem => "上午或下午",
        DockCollapseRegion => "折叠区域",
        DockEmptyStack => "将面板拖放到此处",
        DockMoveFloating => "移动浮动面板",
        DockResizeFloating => "调整浮动面板大小",
        DockSplitLeft => "停靠到左侧",
        DockSplitRight => "停靠到右侧",
        DockSplitTop => "停靠到上方",
        DockSplitBottom => "停靠到下方",
        SplitResizeHandle => "调整窗格大小",
        StatusStale => "已过期",
        ScrollbarVertical => "垂直",
        ScrollbarHorizontal => "水平",
        WindowMinimize => "最小化",
        WindowMaximize => "最大化",
        WindowRestore => "还原",
        WindowClose => "关闭",
        BreadcrumbHiddenOne => "隐藏了 1 层",
        BreadcrumbHiddenMany => "隐藏了 {0} 层",
        AnchorMoreSections => "更多章节",
        PaginationFirst => "第一页",
        PaginationPrevious => "上一页",
        PaginationNext => "下一页",
        PaginationLast => "最后一页",
        PaginationMorePageOne => "还有 1 页",
        PaginationMorePages => "还有 {0} 页",
        PaginationPageOfTotal => "第 {0} 页，共 {1} 页",
        PaginationPage => "第 {0} 页",
        WizardBack | BrowserBack => "后退",
        WizardNext => "下一步",
        WizardFinish => "完成",
        WizardReturnsTo => "返回到",
        ImageViewerNotSupplied => "尚未提供 — {0}",
        ImageViewerPrevious => "上一张图片",
        ImageViewerNext => "下一张图片",
        ImageViewerContain => "完整显示",
        ImageViewerCover => "填满区域",
        ImageViewerSizeUnknown => "尺寸未知",
        ImageViewerDimensionsAndScale => "{0} · {1}",
        ImageViewerEmpty => "没有图片",
        AvatarImageUnavailable => "图片不可用",
        MarkdownImageAlt => "图片",
        MarkdownImageNotFetched => "尚未获取 — {0}",
        MarkdownPlainText => "纯文本",
        MarkdownTask | AgentRunCanvasTask => "任务",
        MarkdownUnrenderedHtml => "未渲染的 HTML",
        MarkdownBlockOne => "1 个块",
        MarkdownBlocks => "{0} 个块",
        MarkdownLineOne | AgentLinesOne => "1 行",
        MarkdownLines | AgentLinesMany => "{0} 行",
        MarkdownRowOne => "1 行",
        MarkdownRows => "{0} 行",
        MarkdownShowMoreOne => "再显示 1 行",
        MarkdownShowMoreMany => "再显示 {0} 行",
        MessageSending => "发送中",
        MessageSent => "已发送",
        MessageDelivered => "已送达",
        MessageRead => "已读",
        MessageStreaming => "流式输出中",
        MessageWriting => "仍在编写",
        MessageMoreOne => "还有 1 条消息",
        MessageMoreMany => "还有 {0} 条消息",
        MessageNewOne => "1 条新消息",
        MessageNewMany => "{0} 条新消息",
        MessageShowMoreOne | AgentMoreLineOne => "还有 1 行",
        MessageShowMoreMany | AgentMoreLineMany => "还有 {0} 行",
        TimeUnknown | TransportTimeUnknown => "时间未知",
        CanvasDisconnect => "断开连接",
        CanvasConnection => "连接",
        CanvasResize => "调整节点大小",
        TransportBuffered => "已缓冲",
        TransportDurationUnknown => "时长未知",
        TransportPosition => "播放位置",
        TransportPlay => "播放",
        TransportPause => "暂停",
        TransportPlaying => "播放中",
        TransportPaused | ProgressPaused => "已暂停",
        TransportBuffering => "等待数据",
        TransportMute => "静音",
        TransportUnmute => "取消静音",
        TransportVolume => "音量",
        TransportRangeOne => "1 个范围",
        TransportRanges => "{0} 个范围",
        TransportPreviousTrack => "上一曲",
        TransportNextTrack => "下一曲",
        MediaFixture => "示例数据",
        MediaNoTransport => "没有播放器",
        MediaNoTransportDetail => "此界面未连接播放器，无法开始播放。",
        MediaNoBackend => "没有播放后端",
        MediaFailed => "无法播放此内容",
        MediaEmpty => "尚未加载内容",
        MediaWaveform | Waveform => "波形",
        VideoNoFrames => "没有画面",
        VideoNoFramesDetail => "播放源持有此视频，但尚未提供视频帧。",
        VideoPoster => "封面",
        VideoPosterDetail => "在收到播放帧之前显示。",
        EffectCinematic => "电影视觉效果",
        EffectAdapterFrame => "由动画适配器渲染。",
        EffectStaticPoster => "已减少动态效果，显示静态封面。",
        EffectParticleFallback => "动画不可用，正在显示内置替代效果。",
        ModelEmpty => "没有模型",
        ModelEmptyDetail => "尚未向查看器提供任何内容。",
        ModelRefused => "此模型被拒绝",
        ModelTooLarge => "{0} 过多：请求 {1}，上限为 {2}。",
        ModelRejected => "超出了此读取器接受的范围（{0}）。",
        ModelFlat => "平面着色",
        ModelWireframe => "线框",
        ModelReset => "重置视图",
        ModelCount | FilterBarResults => "{0} {1}",
        ModelMeshes => "网格",
        ModelVertices => "顶点",
        ModelTriangles => "三角形",
        ModelCamera => "偏航角 {0}°，俯仰角 {1}°",
        SelectPlaceholder | CascaderPlaceholder => "选择",
        SelectClear | GridClearSelection => "清除选择",
        ComboboxNoMatch => "没有与“{0}”匹配的选项",
        ComboboxCreateHint => "按回车键添加为新值。",
        ComboboxClosedHint => "此字段只接受已提供的选项。",
        CascaderUnstarted | ServerOfferingsUnasked | StateViewIdle => "尚未发起请求",
        CascaderEmpty => "没有选项",
        CascaderUnavailable => "选项不可用",
        CascaderError => "无法加载选项",
        DropzoneRefusal => "此区域不接受该内容。",
        SchemaFilesChoose => "选择文件",
        SchemaFilesDrop => "将文件拖放到此处",
        SchemaFileMaximumOne => "此字段最多容纳 1 个文件。",
        SchemaFilesMaximum => "此字段最多容纳 {0} 个文件。",
        SchemaFilesRemove => "移除所选文件",
        SchemaListAdd => "添加项目",
        SchemaListItem => "项目 {0}",
        SchemaListMoveUp => "上移项目",
        SchemaListMoveDown => "下移项目",
        SchemaListRemove => "移除项目",
        FilterBarLabel => "筛选条件",
        FilterBarAdd => "添加筛选条件",
        FilterBarClear | NotificationsClearAll => "全部清除",
        FilterBarCounting | SearchCounting => "统计中…",
        FilterBarResultOne | SearchHitOne => "1 条结果",
        FilterBarResultsMany | SearchHitMany => "{0} 条结果",
        InlineEditPlaceholder => "空",
        KeybindingUnbound => "未绑定",
        KeybindingPrompt => "请按快捷键…",
        KeymapAdd => "添加另一个快捷键",
        KeymapRemove => "移除",
        KeymapReset => "恢复默认设置",
        KeymapEffective => "当前绑定",
        KeymapDefaults => "默认设置",
        KeymapResultOne => "1 条命令",
        KeymapResultCount => "{0} 条命令",
        KeymapEmpty => "没有可显示的快捷键",
        NumberDecrease => "减少",
        NumberIncrease => "增加",
        NumberNotANumber => "这不是数字。",
        NumberBelowMinimum => "允许的最小值为 {0}。",
        NumberAboveMaximum => "允许的最大值为 {0}。",
        SettingsManagedBy => "由 {0} 管理",
        SettingsInapplicable => "此处不可用",
        SettingsEmpty => "没有可用设置",
        SettingsNoResults => "没有与搜索匹配的设置",
        SettingsResultOne => "1 项设置",
        SettingsResultMany => "{0} 项设置",
        TagInputPlaceholder => "添加",
        TagInputDuplicate => "“{0}”已存在",
        TagInputFull => "此字段最多容纳 {0} 项，未添加“{1}”",
        TagInputUsed => "已使用 {0} 项，共 {1} 项",
        TagRemove | UploadRemove => "移除 {0}",
        DescriptionUnknown | GameGaugeUnknown => "未知",
        DescriptionNotApplicable | PermissionNotApplicable => "不适用",
        DescriptionCopy => "复制 {0}",
        DescriptionCharacterOne => "1 个字符",
        DescriptionCharacters => "{0} 个字符",
        CountOfTotal | TextAreaCount | RatingValue => "{0} / {1}",
        PalettePlaceholder => "输入命令",
        PaletteNoMatch => "没有与“{0}”匹配的命令",
        PaletteEmptyDetail => "此处列出了应用程序收到的所有命令。",
        KbdSuper => "Win",
        KbdControl => "Ctrl",
        KbdAlt => "Alt",
        KbdShift => "Shift",
        KbdFunction => "Fn",
        KbdSpace => "空格",
        KbdBackspace => "退格",
        KbdDelete => "删除",
        KbdEscape => "Esc",
        KbdEnter => "回车",
        KbdPageDown => "下一页",
        KbdPageUp => "上一页",
        KbdTab => "Tab",
        KbdLeft => "左",
        KbdRight => "右",
        KbdUp => "上",
        KbdDown => "下",
        GridSelectedNoun => "已选",
        GridSelectAllLoaded => "选择所有已加载行",
        GridSelectAllTotal => "选择全部 {0} 项",
        GridSelectionCounts => "已加载 {1} 项，选中 {0} 项，总计 {2} 项",
        GridResizeColumn => "调整 {0} 的宽度",
        GridLoadingRows => "正在加载行",
        GridLoadFailed => "无法加载行",
        GridEmpty => "没有行",
        DiagnosticsUnstarted => "尚未请求诊断",
        DiagnosticsEmpty => "没有诊断信息",
        DiagnosticsNoMatch => "没有与筛选条件匹配的诊断",
        DiagnosticsUnavailable => "诊断不可用",
        DiagnosticsError => "无法加载诊断",
        DiagnosticsFilterField => "严重程度",
        DiagnosticsFilterOperator => "为",
        DiagnosticsSeverityError | CodeLineError => "错误",
        DiagnosticsSeverityWarning => "警告",
        DiagnosticsSeverityInformation => "信息",
        DiagnosticsSeverityHint => "提示",
        DragFileOne => "1 个文件",
        DragFileMany => "{0} 个文件",
        DropPending => "正在等待移动许可。按 Escape 取消。",
        DropRefused => "移动被拒绝。可再次拖动重试。",
        DropTimedOut => "移动请求超时。可再次拖动重试。",
        DropCancelled => "移动已取消。可再次拖动重试。",
        CopyDone => "已复制",
        CopyFailed => "未复制",
        CopyFailedDetail => "剪贴板未接受此内容。",
        CopyVerificationUnavailable => "写入已提交；无法验证：{0}",
        ApprovalDecline => "拒绝",
        ApprovalApproveOnce => "批准一次",
        ApprovalAlwaysSession => "在本次会话中始终批准",
        ApprovalAlwaysTool => "始终批准 {0}",
        ApprovalAlwaysPath => "在 {0} 中始终批准",
        ApprovalAlwaysHost => "在主机 {0} 上始终批准",
        ApprovalStanding => "持续授权",
        ApprovalDeclined => "已拒绝",
        ApprovalApproved => "已批准：{0}",
        ApprovalOnceScope => "仅限本次",
        ApprovalExpired => "此请求在收到答复前已过期",
        ApprovalSuperseded | ClarificationSuperseded => "已被 {0} 替代",
        ClarificationPickOne => "选择一项",
        ClarificationPickMany => "选择所有适用项",
        ClarificationAnswer => "回答",
        ClarificationSkip => "让智能体决定",
        ClarificationAnswered => "已回答",
        ClarificationSkipped => "你已将此决定交给智能体",
        ClarificationWithdrawn => "不再需要：{0}",
        ClarificationNoOptions => "未提供候选项，无法选择。",
        PermissionAllowed => "允许",
        PermissionDenied => "拒绝",
        PermissionAsk => "每次询问",
        PermissionSubjectHeading => "主体",
        PermissionInherited => "继承自 {0}",
        PermissionSetHere => "在此设置",
        CostMeasured => "{0}",
        CostEstimated => "{0}（估算）",
        CostEstimateMark => "估算",
        CostUnavailable
        | GameGaugeUnavailable
        | GameObjectiveUnavailable
        | GameAbilityUnavailable
        | StateViewUnavailable => "不可用",
        CostLastVerified => "上次确认 {0}",
        ContextUnknownLimit => "上限未知",
        GamePartyDuplicateMember => "队伍成员 {0} 出现了多次。",
        GamePartyDuplicateGauge => "队伍成员 {0} 有多个名为 {1} 的仪表。",
        GameObjectiveLocked => "已锁定",
        GameObjectiveActive => "进行中",
        GameObjectiveCompleted => "已完成",
        GameObjectiveFailed | TraceFailed | ServerFailed | AgentFailed | StageFailed
        | UploadFailed => "失败",
        GameObjectiveDuplicate => "目标 {0} 出现了多次。",
        GameObjectiveDanglingParent => "目标 {0} 指定了不存在的父目标 {1}。",
        GameObjectiveCycle => "目标层级在 {0} 处存在循环。",
        GameAbilityCooldown => "冷却：{0}",
        GameAbilityDisabled => "已禁用",
        GameAbilityCharges => "可用次数：{0}",
        GameAbilityCost => "消耗：{0}",
        GameAbilityDuplicate => "技能 {0} 出现了多次。",
        GameRewardHidden => "奖励未揭晓",
        GameRewardRevealed => "奖励已揭晓",
        GameRewardClaimed => "奖励已领取",
        GameRewardUnavailable => "奖励不可用",
        GameRewardReveal => "揭晓",
        GameRewardClaim => "领取",
        GameRewardQuantity => "×{0}",
        GameRewardDuplicateItem => "奖励物品 {0} 出现了多次。",
        JsonWithheld => "未披露",
        JsonRootValue => "值",
        JsonShapeEntryOne => "1 个条目",
        JsonShapeEntries => "{0} 个条目",
        JsonShapeItemOne => "1 个项目",
        JsonShapeItems => "{0} 个项目",
        JsonShapeValue => "一个值",
        JsonIdentityRequired => "对象成员需要唯一标识",
        JsonIdentityDetail => "重复键需要调用方提供唯一的成员标识。文档未被更改。",
        SchemaNoChoices => "未提供选项，无法选择。",
        SchemaNeedsAdapter => "此字段需要宿主提供日期适配器。",
        SchemaNeedsHost => "此字段需要宿主策略才能填写。",
        ChartEmpty => "没有可绘制的系列",
        ChartLegend => "图例",
        ChartInvalidData => "{0}：提供的图表数据无效",
        ChartInvalidReference => "提供的图表参考线或区间无效",
        ChartStale => "显示上次确认的读数 · {0}",
        TagInputOverflow => "+{0}",
        GridSummary => "汇总",
        TraceEmpty => "没有可显示的跨度",
        TracePending => "等待中",
        TraceRunning | AgentRunning => "运行中",
        TraceSucceeded | AgentSucceeded => "成功",
        TimeUtcValue => "{0} 毫秒（UTC）",
        TimeSelection => "时间选择",
        RangeSelectionStart => "选区起点",
        RangeSelectionEnd => "选区终点",
        RangeSelectionEmpty => "未选择范围",
        RangeSelectionRange => "所选范围：{0} 至 {1}",
        RangeSelectionPreview => "选区预览：{0} 至 {1}",
        TimeSelectionEmpty => "未选择时间",
        TimeSelectionRange => "所选时间：{0} 至 {1}",
        TimeSelectionPreview => "时间选择预览：{0} 至 {1}",
        RangeSelectionInstructions => {
            "拖动以创建，按住 Shift 拖动以替换，在选区内拖动以移动，或拖动手柄以调整范围"
        }
        TraceInterval => "开始：{0}；结束：{1}",
        TraceNormalizedInterval => "开始：{0}；结束：{1}（归一化）",
        TraceReadout => "{0} · {1}\n{2}",
        TraceDuration => "耗时：{0}",
        HeatmapLess => "较少",
        HeatmapMore => "较多",
        HeatmapMissing => "未观测",
        HeatmapEmpty => "没有活动",
        HeatmapUnavailable => "活动数据不可用",
        HeatmapInvalidDomain => "热力图值域必须为有限值且严格递增",
        HeatmapDomainOverflow => "热力图值域无法表示",
        HeatmapOutsideDomain => "热力图观测值超出声明的值域",
        HeatmapReadingOverflow => "热力图观测值无法表示",
        HeatmapDuplicateAxis => "热力图坐标轴标识重复",
        HeatmapDuplicateCell => "热力图单元格标识或坐标重复",
        HeatmapUnknownCoordinate => "未知的热力图行或列",
        HeatmapColorDomain => "颜色值域",
        HeatmapDomainLegend => "{0} / {1} / {2}；缺失值不着色",
        HeatmapCellReading => "{0}：{1}",
        PlotBoxLow => "{0} · 下须端点",
        PlotBoxQ1 => "{0} · 第一四分位数",
        PlotBoxMedian => "{0} · 中位数",
        PlotBoxQ3 => "{0} · 第三四分位数",
        PlotBoxHigh => "{0} · 上须端点",
        PlotBoxLowerWhisker => "{0} · 下须",
        PlotBoxUpperWhisker => "{0} · 上须",
        PlotBoxTop => "{0} · 箱体上边界",
        PlotBoxBottom => "{0} · 箱体下边界",
        PlotBoxOutlier => "{0} · 离群值",
        PlotSubtotal => "{0}（小计）",
        PlotRangeLabel => "{0} · {1}–{2}",
        GeographyCoordinateBounds => "坐标超出投影的有限范围",
        GeographyAntimeridianEdge => "请将跨越反子午线的边拆分为局部多边形",
        GeographyInvalidRing => "环必须闭合、简单、非退化，且顶点不能重复",
        GeographyInvalidHoles => "孔洞必须严格位于内部、互不重叠，不能嵌套或接触",
        GeographyDuplicateIdentity => "地理要素和点的标识必须非空且唯一",
        GeographyInvalidValue => "数值必须有限且位于声明的递增颜色范围内",
        GeographyInvalidViewport => "视口中心必须位于有限的单位世界范围内，缩放范围为 1..=64",
        GeographyInvalidGeoJson => {
            "不支持此 GeoJSON：需带标识的二维 WGS84 Polygon、MultiPolygon 或 Point 要素，属性为对象或 null"
        }
        GeographyDocumentLimit => "GeoJSON 超出 32 MiB 文档大小限制",
        GeographyInvalidSimplification => "简化容差必须有限，范围为投影单位世界的 0..=0.01",
        ColorHue => "色相",
        ColorSaturation => "饱和度和亮度",
        ColorAlpha => "不透明度",
        ColorHex => "十六进制",
        ColorCurrent => "当前颜色",
        ColorPresets => "预设",
        ColorRecent => "最近使用",
        GraphMinimap => "概览",
        GraphMinimapPosition => "水平 {0}%；垂直 {1}%。",
        GraphFit => "适应视图",
        GraphSnap => "吸附到网格",
        GraphArrange => "排列",
        GraphRouteObstructed => "未找到避开障碍的路径",
        GraphRouteSearchLimited => "路径搜索已达到上限",
        GraphEdgeDescription => "{0}；状态：{1}",
        GraphEdgeIdle => "空闲",
        GraphEdgeActive => "活动中",
        GraphEdgeSucceeded => "已成功",
        GraphEdgeFailed => "已失败",
        PromptEmpty => "没有模板",
        PromptUnavailable => "模板不可用",
        PromptFailed => "无法加载模板",
        FeedbackUp => "有帮助",
        FeedbackDown => "没有帮助",
        ArtifactEmpty => "没有产物",
        ArtifactUnavailable => "产物不可用",
        ArtifactLoading => "正在准备产物",
        KanbanEmpty => "没有卡片",
        KanbanUnavailable => "看板不可用",
        KanbanAdd => "添加到 {0}",
        KanbanMoveHere => "将 {0} 移动到 {1}",
        KanbanOverLimit => "超出了 {0} 的上限",
        MetricEmpty | GaugeEmpty | SparklineEmpty => "没有读数",
        MetricUnavailable | SparklineUnavailable => "读数不可用",
        MetricError | SparklineError => "无法加载读数",
        RadarEmpty => "没有可绘制的轴",
        WaveformEmpty => "没有采样数据",
        WaveformUnavailable => "包络数据不可用",
        MicroHeartbeat => "心跳",
        MicroBounce => "弹跳",
        MicroWobble => "摇晃",
        MicroPop => "弹出",
        MicroSparkle => "闪烁",
        FormRequired | SchemaRequiredMissing => "此字段为必填项。",
        FormEmail => "请输入电子邮件地址。",
        FormMinLengthOne => "请至少输入 1 个字符。",
        FormMinLengthMany => "请至少输入 {0} 个字符。",
        FormFieldsDiffer => "两者不匹配。",
        SchemaUnrenderableOne => "此处无法显示 1 个字段。",
        SchemaUnrenderableMany => "此处无法显示 {0} 个字段。",
        ServerConnected => "已连接",
        ServerConnecting => "连接中",
        ServerDisconnected => "已断开连接",
        ServerDisabled => "已关闭",
        ServerTools => "工具",
        ServerSkills => "技能",
        ServerResources => "资源",
        ServerOfferingsUnaskedDetail => "尚未查询此连接提供的功能。",
        ServerOfferingsAsking => "正在查询此连接提供的功能",
        ServerOfferingsNone => "此连接未提供任何功能",
        ServerOfferingsNoneDetail => "已收到答复，结果为空。",
        ServerOfferingsUnavailable => "此连接提供的功能未知",
        ServerEmpty => "没有连接",
        ServerEmptyDetail => "尚未连接任何内容。",
        AgentDocumentEmpty => "此文档为空",
        AgentDocumentUnavailable => "文档不可用",
        AgentDocumentFailed => "无法构建文档",
        AgentArguments => "参数",
        AgentResult => "结果",
        AgentPendingApproval => "等待批准",
        AgentNoOutput => "此工具未返回内容",
        AgentTruncated => "已显示 {0} 行，共 {1} 行",
        AgentPlan => "计划",
        AgentPlanReason => "{0} — {1}",
        AgentStepsDoneOne => "已完成 1 步",
        AgentStepsDoneMany => "已完成 {0} 步",
        AgentReasoningWithheld => "推理未披露",
        AgentReasoningThinking => "思考中",
        AgentReasoningAbsent => "未返回推理内容",
        AgentThinking => "思考中…",
        AgentThought => "思考",
        AgentThoughtFor => "思考了 {0}",
        AgentIdle => "空闲",
        AgentStarting => "启动中",
        AgentPlanning => "规划中",
        AgentUsingTool => "正在使用 {0}",
        AgentSpeaking => "发言中",
        AgentAggregating => "正在汇总结果",
        AgentWaitingInput => "等待输入",
        AgentWaitingDependency => "等待依赖项",
        AgentWaitingAgent => "等待其他智能体",
        AgentWaitingRateLimit => "等待速率限制解除",
        AgentBlockedBecause => "受阻：{0}",
        AgentCancelling => "取消中",
        AgentPartialBecause => "部分完成：{0}",
        AgentFailedBecause => "失败：{0}",
        AgentRefusedBecause => "拒绝：{0}",
        AgentCancelled | UploadCancelled => "已取消",
        AgentTimedOutBecause => "超时：{0}",
        AgentUnavailableBecause => "不可用：{0}",
        AgentIssueMissingRoot => "缺少根智能体 {0}",
        AgentIssueDuplicateAgent => "智能体标识 {0} 重复",
        AgentIssueDuplicateTask => "任务标识 {0} 重复",
        AgentIssueDuplicateLink => "运行关系标识 {0} 重复",
        AgentIssueMissingTaskOwner => "任务 {0} 引用了不存在的所有者 {1}",
        AgentIssueMissingLinkEndpoint => "运行关系 {0} 引用了不存在的端点 {1}",
        AgentIssueSelfLink => "运行关系 {0} 引用了自身",
        AgentRunCanvasAgent => "智能体",
        AgentRunCanvasInvocationKind => "调用",
        AgentRunCanvasInvocation => "调用 {0}",
        AgentRunCanvasInvocationPending => "尚未提供调用详情",
        AgentRunCanvasResults => "结果",
        AgentRunCanvasConflicts => "冲突",
        AgentRunCanvasSpawn => "创建",
        AgentRunCanvasDelegation => "委派",
        AgentRunCanvasDependency => "依赖",
        AgentRunCanvasHandoff => "交接",
        AgentRunCanvasReport => "报告",
        AgentRunCanvasAggregation => "汇总",
        AgentRunCanvasRetry => "重试",
        TabDirty => "有未保存的更改",
        TabSaving => "保存中",
        TabClose => "关闭 {0}",
        TabMoreTabs => "更多标签页",
        OutlineMarks => "{0} 个位置",
        QueryPlaceholder => "搜索",
        SearchPlaceholder => "查找",
        SearchNoHits => "没有结果",
        SearchNotSearched => "尚未搜索",
        SearchTooMany => "超过 {0}",
        SearchClear => "清除查询",
        FindReplaceClose => "关闭查找和替换",
        SearchNext => "下一条结果",
        SearchPrevious => "上一条结果",
        SearchCaseSensitive => "区分大小写",
        SearchWholeWord => "全字匹配",
        ReplacePlaceholder => "替换为",
        ReplaceOne => "替换",
        ReplaceAllCounted => "替换全部 {0} 项",
        ReplaceAllUncounted => "全部替换",
        ReplaceAllUncountable => "尚未统计结果，无法确定将更改多少项。",
        NotificationsTitle => "通知",
        NotificationsEmpty => "没有通知",
        NotificationsEmptyDetail => "收到过的通知保留在此处。",
        NotificationsMarkAllRead => "全部标为已读",
        NotificationsUnread => "未读",
        NotificationsUnreadOne => "1 条未读",
        NotificationsUnreadCount => "{0} 条未读",
        FailureTitle => "无法显示此面板",
        FailureAttempts => "已尝试 {0} 次",
        FailureRetrying => "正在重试",
        StateViewQueued => "等待开始",
        StateViewBlocked => "等待答复",
        StateViewCancelled => "已撤回",
        StateViewEmpty => "此处没有内容",
        StateViewStillWorking => "耗时比平时更长",
        StateViewRefreshing => "刷新中",
        ProgressCancel => "取消",
        ProgressStalled => "已停滞",
        StagePending => "未开始",
        StageActive => "进行中",
        StageDone => "已完成",
        OutcomeSuccess => "已结束",
        OutcomePartial => "已结束，但有失败项",
        OutcomeFailed => "未能完成",
        StaleUpdated => "上次确认：{0}",
        CodeLineAdded => "已添加",
        CodeLineRemoved => "已移除",
        CodeLineChanged => "已更改",
        CodeLineHighlighted => "已高亮",
        CodeEmpty => "没有可显示的内容",
        LogFollow => "跟随输出",
        LogPause => "暂停输出",
        LogFollowing => "正在跟随最新内容",
        LogPaused => "已暂停跟随",
        LogEmpty => "没有日志条目",
        LogUnavailable => "日志不可用",
        LogError => "无法加载日志",
        TerminalStarting => "正在启动会话",
        TerminalUnavailable => "终端不可用",
        TerminalError => "会话已结束",
        TerminalGrid => "终端输出",
        DiffFile => "文件",
        DiffHunk => "差异块",
        DiffContextLine => "上下文行",
        DiffChangedLine => "已更改的行",
        DiffEmpty => "没有差异",
        DiffExpandHunk => "显示更多上下文",
        DiffNoteAdded => "新文件",
        DiffNoteRemoved => "已删除",
        DiffNoteRenamed => "原名称为 {0}",
        DiffNoteBinary => "未显示二进制文件",
        DiffNoteMode => "模式已更改为 {0}",
        DiffNote => "文件说明",
        TreeChildrenUnavailable => "无法加载此分支",
        TreeEmpty | CarouselEmpty => "没有项目",
        RatingStar => "{0} 星",
        RatingUnrated => "尚未评分",
        RatingClear => "清除评分",
        TransferAvailable => "可选项",
        TransferSelected => "已选项",
        TransferSearch => "筛选项目",
        TransferMoveToTarget => "将选中项移至已选列表",
        TransferMoveToSource => "将选中项移至可选列表",
        CarouselPrevious => "上一项",
        CarouselNext => "下一项",
        CarouselPage => "跳转到第 {0} 项",
        MentionSuggestions => "提及建议",
        MentionIdle => "尚未请求提及建议",
        MentionLoading => "正在加载提及建议",
        MentionRefreshing => "正在更新提及建议",
        MentionEmpty => "没有提及建议",
        MentionNoMatch => "没有与搜索匹配的提及项",
        MentionUnavailable => "提及建议不可用",
        MentionError => "无法加载提及建议",
        MentionStale => "建议可能已过期",
        RichTextPlaceholder => "开始编写…",
        RichTextToolbar => "格式",
        RichTextUndo => "撤销",
        RichTextRedo => "重做",
        RichTextBold => "粗体",
        RichTextItalic => "斜体",
        RichTextUnderline => "下划线",
        RichTextStrike => "删除线",
        RichTextCode => "代码",
        RichTextLink => "链接",
        RichTextUnorderedList => "项目符号列表",
        RichTextOrderedList => "编号列表",
        RichTextAlignStart => "起始端对齐",
        RichTextAlignCenter => "居中对齐",
        RichTextAlignEnd => "末端对齐",
        RichTextIndent => "增加缩进",
        RichTextOutdent => "减少缩进",
        RichTextBullet => "•",
        RichTextOrderedMarker => "{0}.",
        DrawerResize => "调整抽屉大小",
        ContextMenuUnavailable => "原生菜单不可用",
        SparklineCurrent => "当前：{0}",
        SparklineMinimum => "最小：{0}",
        SparklineMaximum => "最大：{0}",
        SparklineRange => "最小 {0}；最大 {1}",
        PerformanceTitle => "性能",
        PerformanceWaiting => "等待帧采样",
        PerformanceUnavailable => "帧计时不可用",
        PerformanceExpand => "显示详情",
        PerformanceCollapse => "隐藏详情",
        PerformanceFps => "绘制频率",
        PerformanceFpsValue => "{0} FPS",
        PerformanceMeanDraw => "平均绘制时间",
        PerformanceP95Draw => "P95 绘制时间",
        PerformanceFrameBudget => "帧时间预算",
        PerformanceOverBudget => "超时绘制次数",
        PerformanceInvalidations => "平均失效次数",
        PerformanceDirtyToDraw => "平均重绘等待时间",
        PerformanceSamples => "采样数",
        PerformanceDrawHistory => "绘制耗时历史",
        PerformanceMilliseconds => "{0} 毫秒",
        UploadUploading | UploadOverall => "上传中",
        UploadDone => "已上传",
        UploadRefused => "未接受",
        UploadCancel => "取消 {0}",
        UploadEmpty => "尚无文件",
        BrowserPanel => "浏览器",
        BrowserForward => "前进",
        BrowserReload => "重新加载",
        BrowserNoAddress => "没有地址",
        BrowserEmpty => "页面没有内容",
        BrowserEmptyDetail => "页面已加载，但内容为空。",
        BrowserUnavailable => "网页内容不可用",
        BrowserNoEngineDetail => "此构建无法显示网页内容。",
        BrowserError => "无法加载",
        BrowserNoViewport => "没有页面视图",
        BrowserNoViewportDetail => "宿主报告页面已就绪，但未提供视图。",
        OfferingCatalogEmpty => "没有可用功能",
        OfferingCatalogNoMatch => "没有匹配的功能",
        OfferingSourceLoading => "{0}：正在加载功能",
        OfferingSourceEmpty => "{0}：没有可用功能",
        OfferingSourceUnavailable => "{0}：功能不可用",
        OfferingSourceError => "{0}：无法加载功能",
        OfferingSourceStale => "{0}：显示上次确认的功能",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn placeholders(text: &str) -> Vec<&str> {
        let mut slots: Vec<_> = text
            .split('{')
            .skip(1)
            .map(|part| {
                let (index, _) = part.split_once('}').expect("closed placeholder");
                assert!(
                    index.parse::<usize>().is_ok(),
                    "positional template: {text}"
                );
                index
            })
            .collect();
        slots.sort_unstable();
        slots
    }

    #[test]
    fn builtin_packs_are_complete_and_preserve_every_placeholder() {
        for &pack in TranslationPack::ALL {
            let strings = pack.strings();
            for &key in StringKey::ALL {
                let translated = pack.text(key);
                assert!(!translated.trim().is_empty(), "{pack:?}: {key:?}");
                assert_eq!(
                    placeholders(translated),
                    placeholders(key.english()),
                    "{pack:?}: {key:?}"
                );
                assert_eq!(strings.text(key).as_ref(), translated);
                if pack == TranslationPack::SimplifiedChinese {
                    assert!(strings.is_overridden(key));
                }
            }
        }
    }

    #[test]
    fn clipboard_verification_refusal_preserves_submission_and_host_reason() {
        let reason = "宿主拒绝读取（policy:{0}）";
        let key = StringKey::CopyVerificationUnavailable;
        let english = TranslationPack::English.strings().format(key, &[reason]);
        let chinese = TranslationPack::SimplifiedChinese
            .strings()
            .format(key, &[reason]);
        assert_eq!(
            english.as_ref(),
            "Clipboard write submitted; verification unavailable: 宿主拒绝读取（policy:{0}）"
        );
        assert_eq!(
            chinese.as_ref(),
            "写入已提交；无法验证：宿主拒绝读取（policy:{0}）"
        );
        for &pack in TranslationPack::ALL {
            let text = pack.strings().format(key, &[reason]);
            assert_ne!(text.as_ref(), pack.text(StringKey::CopyDone));
            assert_ne!(text.as_ref(), pack.text(StringKey::CopyFailedDetail));
        }
    }

    #[test]
    fn builtin_packs_reorder_values_without_changing_facts_or_caller_overrides() {
        let mut strings = TranslationPack::SimplifiedChinese.strings();
        assert_eq!(
            strings
                .format(StringKey::GridSelectionCounts, &["2", "7", "19"])
                .as_ref(),
            "已加载 7 项，选中 2 项，总计 19 项"
        );
        assert_eq!(
            strings
                .format(StringKey::ApprovalAlwaysPath, &["/work"])
                .as_ref(),
            "在 /work 中始终批准"
        );
        assert_eq!(
            strings
                .format(StringKey::ApprovalAlwaysHost, &["example.test"])
                .as_ref(),
            "在主机 example.test 上始终批准"
        );
        assert_ne!(
            strings.text(StringKey::CopyDone),
            strings.text(StringKey::CopyFailed)
        );
        assert_ne!(
            strings.text(StringKey::AttachmentReady),
            strings.text(StringKey::AttachmentProcessing)
        );
        assert_ne!(
            strings.text(StringKey::BrowserUnavailable),
            strings.text(StringKey::BrowserEmpty)
        );
        strings.set(StringKey::Copy, "复制内容");
        assert_eq!(strings.text(StringKey::Copy).as_ref(), "复制内容");
        assert_eq!(
            TranslationPack::SimplifiedChinese
                .strings()
                .text(StringKey::Copy)
                .as_ref(),
            "复制"
        );
        strings.clear(StringKey::Copy);
        assert_eq!(
            strings.text(StringKey::Copy).as_ref(),
            "Copy",
            "clear retains the existing English-reset contract"
        );
    }
}
